- .changeset/five-icons-study.md
- packages/composables/src/useAddress.ts
- packages/nuxt3-module/plugin.ts
- templates/vue-demo-store/app.vue
- templates/vue-demo-store/pages/wishlist.vue
closes #150 
- fixed problem with context on SSR reload
- improved performance of initial page load from demo store, as context no longer needs to reload before wishlist
- lighthouse score should go up as we're having less reqyests
Before: 
After:
Before:
After:
I had a lot of items in wishlist so added clearWishlist button
> fix: ssr context from cookies

- .changeset/polite-squids-flow.md
- packages/composables/src/usePrice.ts
- packages/composables/src/useSessionContext.ts
closes #164 
Fixes hydration error causing prices to be visible without currency
> fix(composables): proper currency and price context on SSR

- .changeset/khaki-seas-sin.md
- packages/nuxt3-module/build.config.ts
- packages/nuxt3-module/package.json
- packages/nuxt3-module/src/utils.ts
- pnpm-lock.yaml
removes a dependency responsible for parsing/reading a package.json. the library was replaced by simple fs read function + JSON.parse.
> fix(nuxt3-module): remove package.json parser

- .changeset/neat-files-jog.md
- examples/blank-playground/src/App.vue
preview: https://stackblitz.com/github/shopware/frontends/tree/fix/async-loading-for-blank-playground-example/examples/blank-playground
> fix(examples): async loading for blank-playground

- templates/vue-demo-store/composables/useMeta.ts
- templates/vue-demo-store/nuxt.config.ts
Removes a temporary fix that was needed for useMeta because of [this issue](https://github.com/vueuse/vueuse/pull/2449).
Tested different pages and was looking at the meta tags in head.
Looks fine after removing these files.
> fix(demo): remove tmp fix useMeta

- .github/workflows/audit-check.yml
- .github/workflows/code-check.yml
New GH action to check audit when invoked:
- manually
- every day at 8:30
- when lockfile is changed on a branch or incoming PR
Additionally, the old check has been removed, so not every PR is checked with the audit. Thanks to this if PRs haven't changed any dependencies should not be blocked by the `audit` command.
> feat: audit check improvements

- .changeset/pink-donuts-join.md
- packages/api-client-next/package.json
fix for api-types not included in npm package
> fix: ship api types with the package

- .changeset/famous-forks-unite.md
- .tazerc.json
- apps/docs/package.json
- examples/example-builder/package.json
- examples/modal-teleport/package.json
- examples/new-api-client/package.json
- package.json
- packages/api-client-next/package.json
- packages/api-gen/package.json
- packages/cms-base/package.json
- packages/composables/package.json
- packages/eslint-config-shopware/package.json
- packages/nuxt3-module/package.json
- packages/typer/package.json
- packages/vue3-plugin/package.json
- patches/@changesets__apply-release-plan@6.1.4.patch
- pnpm-lock.yaml
- templates/astro/package.json
- templates/vue-blank/package.json
- templates/vue-demo-store/package.json
- templates/vue-vite-blank/package.json
* bump dependencies
* dismiss current audit problem, not affecting this repo
* new patch for changesets, updated after the last release (migrated from https://github.com/changesets/changesets/pull/1047)
> chore: bump dependencies

- .changeset/dull-steaks-beam.md
- .changeset/eight-rivers-peel.md
- .changeset/gold-rockets-shave.md
- packages/cms-base/components/SwProductCard.vue
- packages/cms-base/components/listing-filters/SwFilterProperties.vue
- packages/cms-base/components/public/cms/element/CmsElementImage.vue
- packages/cms-base/components/public/cms/element/CmsElementImageGallery.vue
- packages/nuxt3-module/plugin.ts
- packages/nuxt3-module/src/index.ts
- pnpm-lock.yaml
- templates/vue-demo-store/app.vue
- templates/vue-demo-store/components/account/AccountMenu.vue
- templates/vue-demo-store/components/account/AccountRegisterForm.vue
- templates/vue-demo-store/components/listing-filters/ListingFiltersProperties.vue
- templates/vue-demo-store/components/product/ProductCard.vue
- templates/vue-demo-store/components/product/ProductSuggestSearch.vue
- templates/vue-demo-store/nuxt.config.ts
- templates/vue-demo-store/pages/checkout/index.vue
edge cache leverage:
Additionaly compare lighthouse:
> feat(vue-demo): leverage edge cache

- apps/e2e-tests/tests/checkForSeoUrl.spec.ts
Related #311 - test for checking `seo-url` during internal navigation
> feat(e2e): add tests for seo url

- .changeset/chilled-moles-grab.md
- packages/cms-base/components/public/cms/block/CmsBlockImageHighlightRow.vue
- packages/cms-base/components/public/cms/block/CmsBlockProductHeading.vue
If you don't use UnoCSS with the "cms-base" package, you will get a critical error message and won't be able to use the package.
The changes provided fix this issue.
This changes also fix #305.
> fix(cms-base): CMS apply error on missing UnoCSS

- .changeset/chilly-shirts-exercise.md
- packages/api-client-next/src/index.ts
- packages/api-client-next/src/transformPathToQuery.test.ts
Fixes query param arrays. This fixes the way how query params are serialized. Previously, array query params were serialized as `?ids=1&ids=2`, now they are serialized as `?ids[]=1&ids[]=2`. This is the proper way of serialization in the Shopware API.
The definition of the endpoints hasn't changed, so you don't need to change anything in your code.
> fix(api-client): query param arrays

- packages/vite-vue-plugin-disable-inputs/README.md
- packages/vite-vue-plugin-disable-inputs/package.json
- pnpm-lock.yaml
- templates/vue-demo-store/nuxt.config.ts
- templates/vue-demo-store/package.json
disables vite plugin for nuxt template.
@patzick - after release, please [mark npm package as deprecated](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions) in package settings with appropriate message.
> feat(vue-demo-store): disable vite plugin

- .changeset/afraid-flowers-search.md
- .changeset/six-weeks-travel.md
- packages/vue3-plugin/README.md
- packages/vue3-plugin/package.json
- pnpm-lock.yaml
- templates/vue-vite-blank/package.json
- templates/vue-vite-blank/src/main.ts
closes: #350 
working stackblitz instance: https://stackblitz.com/github/shopware/frontends/tree/feat/deprecate-vue3-plugin/templates/vue-vite-blank
after release, only requirement is to set the package as deprecated in npm settings
> feat: deprecate vue3 plugin

- .changeset/calm-hounds-heal.md
- packages/api-client-next/package.json
- packages/api-client-next/src/adminSessionData.test.ts
- packages/api-client-next/src/index.ts
Idea from @jleifeld
Creates the ability to access and change admin client session data for testing purposes. This comes with fixture example of creating a new API instance per test
> feat(api-client): access admin client session data and change in in the runtime

- .changeset/chilly-cameras-speak.md
- packages/composables/src/useListing.ts
I'm marking this as a bugfix, as I assume it was not intended for the function to not have a query parameter. Should close #379.
The current problem is that filters, if set, will not be applied to the query on loadMore. This means, that when using a non-pagination style of content fetching, the functionality breaks there. 
I was trying to follow the contributing guidelines as well as I could, but please check if I missed something when making this edit (like documentation or something like that).
> fix(composables): adds parameter to loadMore to accept an optional query

- examples/express-checkout/package.json
- examples/express-checkout/src/App.vue
- bump deps
- changes the `loadScript` argument.
- adds some info on how to proceed with the plugin -> using own credentials works better for now
> fix(examples): express checkout upgrade

- .changeset/gentle-vans-tell.md
- packages/nuxt3-module/plugin.ts
> fix(nuxt3-module): problem with autoloading composables within shopware plugin

- .changeset/blue-mice-switch.md
- packages/cms-base/components/SwProductListingFilters.vue
- packages/cms-base/components/public/cms/section/CmsSectionSidebar.vue
> fix(vue-demo): product listing structure

- .github/workflows/failed-job-check.yml
- .github/workflows/lighthouse.yml
- .github/workflows/vue-blank.yml
- .github/workflows/vue-demo-store.yml
- .github/workflows/vue-vite-blank.yml
Add slack notification only on fail jobs (Code examples, Lighthouse CI, Vue vite blank, Vue Blank, Vue demo store, Audit check)
!!! add webhook slack channel url to github secret (name FAIL_SLACK_URL)
After taking all PR actions, you can run the unsubscribe command for this repository from the Slack channel
> feat(e2e): add slack notification only on fail

- .github/workflows/code-examples.yml
- apps/e2e-tests/examples.config.ts
- apps/e2e-tests/package.json
- apps/e2e-tests/tests/checkCodeExamples.spec.ts
closes: #428 
- only one device for tests left
- changes a selector for stackblitz "play button" to be more general, into `button[class^='ClickToLoad-actionBtn']` without any hardcoded ids
- separates a playwright config for code examples
- adds array of ignored examples that should be tested and fired only locally (because of its complexity)
> fix(examples): minor test improvements

- .changeset/tame-ears-joke.md
- examples/adyen-dropin-component/components/AdyenCreditCard.vue
- examples/adyen-dropin-component/plugins/AdyenCheckout.client.ts
- examples/mollie-credit-card/src/runtime/plugins/plugin.client.ts
- examples/mollie-credit-card/src/runtime/plugins/plugin.server.ts
- packages/nuxt3-module/plugin.ts
This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.
> fix: import nuxt composables from #imports

- packages/cms-base/nuxt.config.ts
- packages/composables/nuxt.config.ts
closes #473 
For some reason, when Nuxt Layer is inside `node_modules`, transpilation is turned off (even though full path is added to transpilation array) it's ommited. This PR should fix that.
> fix: missing transpilation for aliases in node_modules

- packages/cms-base/components/listing-filters/SwFilterPrice.vue
- templates/vue-demo-store/components/listing-filters/ListingFiltersPrice.vue
closes #457
The watch was also executed with the default value of 0, this we skip now and only change when a real user interaction took place. Also, a max or min price filter with 0 is not something retailers like to filter for so I guess it is safe to skip it in that case.
> fix(demo): do not execute watch if 0

- templates/vue-demo-store/README.md
This PR includes updates to the vue-demo-store template README for formatting and clarity when the template is published on the Vercel templates page.
- Moved Stackblitz deploy button to the top and removed header since the button will not render within the template detail page on vercel.com
- Provided additional clarity on Docker steps
- Replaced relative links with absolute URLs to avoid 404s when content is imported to vercel.com
- Miscellaneous nomenclature and grammar fixes
> docs: update README.md

- .changeset/fifty-bats-type.md
- pnpm-lock.yaml
- templates/vue-demo-store/nuxt.config.ts
- templates/vue-demo-store/package.json
Upgrades @nuxjs/i18n module to the latest rc.11 version.
- removes JIT warning (`compile.jit: false` config is not required anymore)
- `jsTsFormatResource` optional config is not required anymore to read translations properly from .ts files
> feat(templates): i18n module upgrade for vue-demo-store

- .changeset/swift-flies-fetch.md
- packages/cms-base/components/public/cms/element/CmsElementText.vue
- packages/cms-base/helpers/html-to-vue/getOptionsFromNode.test.ts
- packages/cms-base/helpers/html-to-vue/getOptionsFromNode.ts
- packages/cms-base/helpers/html-to-vue/renderToHtml.ts
- packages/cms-base/helpers/html-to-vue/renderer.ts
- packages/cms-base/package.json
- packages/cms-base/vitest.config.ts
- pnpm-lock.yaml
This is alternative resolution to #540
- refactored `getOptionsFromNode` with code simplification
- added vitest to the package
- added error message when there's some error there, component is still rendered but for example without styles
- fully tested method, 100% coverage
- moved `resolveUrl` as param, composables should not be used inside methods, so injection potentially was invoked in every node + potentially Urls could work in the wrong way
> fix(cms-base): improve getOptionsFromNode helper

- .changeset/unlucky-turkeys-call.md
- packages/helpers/src/cms/getCmsLayoutConfiguration.spec.ts
- packages/helpers/src/cms/getCmsLayoutConfiguration.ts
- packages/helpers/src/cms/index.ts
- templates/vue-demo-store/uno.config.ts
> fix(vue-demo-store): visibility classes

- .github/workflows/audit-check.yml
- .github/workflows/check-pr-title.yml
- .github/workflows/code-check.yml
- .github/workflows/code-examples.yml
- .github/workflows/codspeed.yaml
- .github/workflows/e2e-tests.yml
- .github/workflows/failed-job-check.yml
- .github/workflows/lighthouse.yml
- .github/workflows/publish-canary.yml
- .github/workflows/release.yml
- .github/workflows/vue-blank.yml
- .github/workflows/vue-demo-store.yml
- .github/workflows/vue-vite-blank.yml
Following the announcement: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
We switch to `macos-14` runners, which should have a big impact on workflows.
> ci: move to macos GH actions

- .changeset/loud-chicken-sin.md
- packages/api-client-next/src/createAdminApiClient.test.ts
- packages/api-client-next/src/createApiClient.test.ts
- packages/api-client-next/src/index.ts
closes #554 
Header `Accept: application/json` should be enabled by default in requests
> fix(api-client): use `Accept: application/json` header by default

- .changeset/happy-doors-love.md
- .changeset/quiet-rockets-laugh.md
- packages/api-client-next/README.md
- packages/api-client-next/src/adminApiClientCredentials.test.ts
- packages/api-client-next/src/adminSessionData.test.ts
- packages/api-client-next/src/createAdminApiClient.test.ts
- packages/api-client-next/src/index.ts
- templates/vue-demo-store/shopware.d.ts
closes: #553 
Replaced additional only token-based `clientData` with `optional `credentials` field.
This way, scripts or apps can provide admin authentication of their choice to be used automatically before invoking any endpoint.
> feat(api-client): provide optional `credentials` field for automatic authentication

- .changeset/quiet-ghosts-itch.md
- packages/api-client-next/package.json
- packages/api-gen/README.md
- packages/api-gen/package.json
- packages/api-gen/src/cli.ts
- packages/api-gen/src/commands/loadSchema.ts
- pnpm-lock.yaml
Adds the possibility to pick API type on schema generation plus uses API client to authenticate and load schema using our apiClient.
> feat(api-gen): added `apiType` option to `loadSchema` command

- .changeset/perfect-shirts-beam.md
- packages/cms-base/components/SwSlider.vue
hotfix solves 500 error on SSR caused by this problem: 
_vue:error H3Error: [nuxt] `setInterval` should not be used on the server. Consider wrapping it with an `onNuxtReady`, `onBeforeMount` or `onMounted` lifecycle hook, or ensure you only call it in the browser by checking `false`._
Bug fix (non-breaking change that fixes an issue) 
[x] Changeset file provided [read more](https://github.com/shopware/frontends/blob/main/CONTRIBUTION.md#changelog-preparation)
> fix(cms-base): prevent using setTimeout on server side for SwSlider

- packages/cms-base/components/SwSlider.vue
- packages/cms-base/components/public/cms/element/CmsElementImage.vue
- packages/cms-base/components/public/cms/element/CmsElementImageGallery.vue
After a hard reload the image gallery was nice but with client navigation, it often happens that the images on PDP looked ugly. With those changes, this is fixed and always "beautiful". :joy: 
closes: #799
This (**current**):
vs
This (**fixed**):
> fix(cms): more beauty image gallery

- packages/cms-base/components/SwProductListingFilters.vue
- packages/cms-base/components/public/cms/element/CmsElementProductListing.vue
- packages/cms-base/components/public/cms/section/CmsSectionSidebar.vue
- templates/vue-demo-store/pages/search.vue
With that changes search and listing using the same flex style (removed grid) to display the products.
It looks much better on the different sizes ... also with fixed max-width elements like CMS pages.
Compare the demo with the preview. You will :heart: it. :smiley:
> fix(cms): unify search and listing style

- packages/cms-base/components/public/cms/CmsPage.vue
- packages/composables/src/useContext.ts
- packages/composables/src/useListing.ts
Alternative to #823
Related: #841
Creates a workaround for listing by creating listing context and addressing it in child components.
This also fixes the bug described in PR above.
@BrocksiNet please check if that covers all the cases you wanted to solve with that PR.
> fix: cached category id in listing state

- .changeset/cyan-bees-relate.md
- packages/composables/src/useProductSearch.ts
Adjust types in `useProductSearch` composable
closes #870
> feat(composable): useProductSearch types

- packages/nuxt3-module/plugin.ts
The object of this PR is to set the secure flag for the `Sw-Context-Token` cookie if possible.
New feature (non-breaking change which adds functionality)
This came up as a minor issue in a pentest of an app using the nuxt3-module.
> feat(nuxt3-module): secure Sw-Context-Token cookie

- .changeset/green-geckos-chew.md
- .changeset/green-pumas-cough.md
- .changeset/stupid-ravens-rhyme.md
- apps/docs/src/getting-started/languages.md
- packages/cms-base/components/SwContactForm.vue
- packages/cms-base/components/SwListingProductPrice.vue
- packages/cms-base/components/SwNewsletterForm.vue
- packages/cms-base/components/SwPagination.vue
- packages/cms-base/components/SwProductAddToCart.vue
- packages/cms-base/components/SwProductCard.vue
- packages/cms-base/components/SwProductListingFilters.vue
- packages/cms-base/components/SwProductPrice.vue
- packages/cms-base/components/SwProductReviews.vue
- packages/cms-base/components/SwProductUnits.vue
- packages/cms-base/components/SwVariantConfigurator.vue
- packages/cms-base/components/listing-filters/SwFilterPrice.vue
- packages/cms-base/components/public/cms/element/CmsElementBuyBox.vue
- packages/cms-base/components/public/cms/element/CmsElementCategoryNavigation.vue
- packages/cms-base/components/public/cms/element/CmsElementProductDescriptionReviews.vue
- packages/cms-base/components/public/cms/element/CmsElementProductListing.vue
- templates/vue-demo-store/app.vue
- templates/vue-demo-store/components/cms/element/CmsElementProductDescriptionReviews.vue
- templates/vue-demo-store/i18n/de-DE/product.json
- templates/vue-demo-store/i18n/en-GB/product.json
- templates/vue-demo-store/i18n/pl-PL/product.json
- templates/vue-demo-store/nuxt.config.ts
- Add `localeId` as an option to change the language
- Make injected translations the most significant priority source
- Add missing product translations
> feat: changes in language switcher

- .changeset/purple-sloths-perform.md
- packages/api-client/src/services/formsService.ts
- packages/api-client/src/services/newsletterService.ts
Adjust `formsService` types
closes: #929
> feat: adjust formsService types

- .changeset/sweet-avocados-beam.md
- packages/api-gen/src/commands/generate.ts
From
```
OrderRouteResponse: {
paymentChangeable?: GenericRecord;
};
```
To
```
OrderRouteResponse: {
paymentChangeable?: {
[key: string]: boolean;
};
};
```
> fix(gen-api): additional properties

- templates/vue-demo-store/components/layout/LayoutSideMenu.vue
- templates/vue-demo-store/components/layout/LayoutTopNavigation.vue
- templates/vue-demo-store/components/layout/LayoutTopNavigationRecursive.vue
- It allows you to use ArrowDown, ArrowUp, and Escape to navigate the top navigation.
- You can now scroll inside the mobile top navigation
New feature (non-breaking change which adds functionality)
Still you could add ArrowLeft and ArrowRight for the top levels.
Also, I did not test this with a 3-level navigation.
First I want to know if there is maybe a better way to do this (discussion).
> feat: keyboard navigation and improved mobile sidebar

- templates/vue-vite-blank/src/apiClient.ts
- templates/vue-vite-blank/src/main.ts
fixes the vue-vite-blank template to run it without having the console errors about deprecation
you can preview the template after update: https://stackblitz.com/github/shopware/frontends/tree/feat/new-hook-vue-vite-blank/templates/vue-vite-blank
> feat(templates): new way of handling a context change for vue-vite-blank

- .changeset/nine-readers-relate.md
- packages/api-gen/README.md
- packages/api-gen/api-gen.schema.json
- packages/api-gen/src/cli.ts
- packages/api-gen/src/commands/validateJson.ts
- packages/api-gen/src/validation-rules/componentsApiAlias.rule.test.ts
- packages/api-gen/src/validation-rules/componentsApiAlias.rule.ts
- packages/api-gen/src/validation-rules/index.ts
- packages/api-gen/vitest.config.ts
With this new command in CLI we can validate JSON schema output with configured rules.
For now, only the first rule is added. Every rule must have 100% test coverage and a description in the schema file.
Example of validation with errors (current store schema):
> feat(api-gen): command to validate json output

- .changeset/metal-clocks-repeat.md
- templates/vue-demo-store/components/account/AccountChangePassword.vue
- templates/vue-demo-store/i18n/de-DE/validations.json
- templates/vue-demo-store/i18n/en-GB/validations.json
- templates/vue-demo-store/i18n/pl-PL/validations.json
- Added missing `same password` error message
- Changed the success message block to reset after each click on the main button
closes #1016
> fix(vue-demo): password reset page

- .changeset/clean-maps-wash.md
- packages/api-client-next/README.md
- packages/api-client-next/src/createAdminApiClient.test.ts
- packages/api-client-next/src/createAdminApiClient.ts
- packages/api-client-next/src/createApiClient.test.ts
- packages/api-client-next/src/createApiClient.ts
- packages/api-client-next/src/tests/RequestParameters.test-d.ts
closes #1022
Support for `ofetch` additional params, like AbortController's signal, timeout, retry etc.
> feat(api-client): expose fetchOptions to extend requests with AbortController, timeout etc.

- apps/docs/package.json
- examples/amazon-pay-button-example/package.json
- examples/example-builder/package.json
- examples/mollie-credit-card/package.json
- examples/new-api-client/package.json
- examples/snippets-middleware/package.json
- examples/use-add-to-cart/package.json
- examples/use-cart/package.json
- examples/use-checkout/package.json
- packages/cms-base/components/SwProductReviews.vue
- packages/cms-base/components/SwSlider.vue
- packages/cms-base/components/public/cms/block/CmsBlockDefault.vue
- packages/cms-base/components/public/cms/block/CmsBlockTextTeaserSection.vue
- packages/cms-base/package.json
- packages/composables/package.json
- packages/nuxt3-module/package.json
- pnpm-lock.yaml
- templates/vue-blank/package.json
- templates/vue-demo-store/package.json
- templates/vue-vite-blank/package.json
Bump to version 5.5. Release notes: https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/
> chore: bump typescript to 5.5

- .changeset/rich-turkeys-approve.md
- templates/vue-demo-store/components/checkout/CheckoutSideCart.vue
Disable button for empty cart
closes #1030
> fix: disable checkout button

- .changeset/fast-planes-warn.md
- templates/vue-demo-store/components/account/AccountMenu.vue
Added closing account menu after clicking outside
closes #1031
> feat(vue-demo): closing account menu

- packages/cms-base/components/SwProductListingFilters.vue
- packages/cms-base/components/public/cms/element/CmsElementSidebarFilter.vue
closes #1065 
display filters on client-only view to avoid hydration errors. This can be improved with the listing refactor
> fix: show filters on client only to avoid hydration errors

- .changeset/fluffy-islands-float.md
- .changeset/witty-zoos-work.md
- examples/adyen-dropin-component/api-types/storeApiTypes.d.ts
- examples/b2b-quote-management/api-types/storeApiTypes.d.ts
- examples/commercial-customized-products/api-types/storeApiTypes.d.ts
- examples/commercial-quick-order/api-types/storeApiTypes.d.ts
- examples/express-checkout/api-types/storeApiTypes.d.ts
- examples/mollie-credit-card/api-types/storeApiTypes.d.ts
- packages/api-client/api-types/storeApiSchema.overrides.json
- packages/api-client/api-types/storeApiTypes.d.ts
- packages/composables/src/useListing.ts
- templates/vue-demo-store/api-types/storeApiTypes.d.ts
replaces #1077 
Special thanks to @fschmtt to point the problem!
This PR is adding patch to OpenAPI schema, where header param was missing, thanks to this running 
`pnpm shopware-api-gen generate --apiType=store` or `pnpm showpare-api-gen validateJson --apiType=store` there is a clear warning what needs to be fixed in the schema. This will help the core to fix the problem and patch it for us for now.
> fix: missing seo url in search endpoint

- .changeset/orange-glasses-worry.md
- .changeset/thick-donkeys-sip.md
- packages/api-client/api-gen.config.json
- packages/api-client/api-types/adminApiSchema.overrides.json
- packages/api-gen/src/commands/generate.ts
- packages/api-gen/src/commands/validateJson.ts
- packages/api-gen/src/jsonOverrideUtils.ts
- packages/api-gen/src/validation-rules/componentsApiAlias.rule.test.ts
- packages/api-gen/src/validation-rules/componentsApiAlias.rule.ts
- fixes problem with overrides loading
- improves validation message suggesting that schema component name might be incorrect
- added more tests for the rule
> fix(api-gen): better validation rule for COMPONENTS_API_ALIAS flag and proper overrides loading

- apps/docs/.vitepress/config.ts
We can avoid some 301 redirects when using the correct links in the sidebar.
Also, tools like [deadlink-checker](https://www.deadlinkchecker.com/website-dead-link-checker.asp) are complaining about this.
> fix(docs): wrong links in sidebar

- apps/docs/src/resources/integrations/commercial/custom-products.md
- examples/commercial-customized-products/README.md
Adds missing README for Custom Products example, and link it in the docs.
> docs: custom products README

- .changeset/rich-lies-tease.md
- packages/api-gen/src/jsonOverrideUtils.ts
Fixes the problem with fetching overrises in json5 format
> fix(api-gen): parse json5 responses for overrides

- packages/api-client-old/package.json
- packages/api-client/package.json
- packages/api-gen/package.json
- packages/cms-base/package.json
- packages/composables/package.json
- packages/composables/vitest.config.ts
- packages/helpers/package.json
- pnpm-lock.yaml
upgraded vitest to 2.0
required small config changes, and reducing coverage in the composables package by a few percent, as coverage detection was improved
> chore: upgrade vitest to 2.x

- .changeset/long-pianos-allow.md
- packages/helpers/src/media/getSrcSetForMedia.test.ts
- packages/helpers/src/media/getSrcSetForMedia.ts
wrong `srcset` attribute causes some problems during loading an image. because the wrong format, like `400w` without a corresponding image, the image was being loaded through a nuxt router as a normal page (in an entrypoint `[...all].vue`).
> fix(helpers): correct srcset for images

- .changeset/sixty-teachers-allow.md
- packages/composables/src/index.ts
- packages/composables/src/useDefaultOrderAssociations.test.ts
- packages/composables/src/useDefaultOrderAssociations.ts
- packages/composables/src/useOrderDetails.ts
another approach of #1184 to allow access and override default order associations
> feat(composables): useDefaultOrderAssociations for accessing associations

- .changeset/smart-bobcats-film.md
- packages/api-gen/src/commands/generate.ts
- packages/api-gen/src/commands/loadSchema.ts
should fix the probelm from the slack channel, where CLI was ignoring the env variable provided by the system and reading only the .env file
> fix(api-gen): reading variables from the process.env instead of the dotenv config

- apps/docs/.vitepress/config.ts
- apps/docs/.vitepress/sidebar.ts
This PR is a start of breaking down https://github.com/shopware/frontends/pull/493 into smaller chunks:
- extracts `themeConfig.sidebar` into `sidebar.ts` so DevHub can [pick](https://github.com/shopware/developer-portal/blob/main/.vitepress/navigation.ts#L125C1-L131C1) statically defined sidebar in/from this repo
- removes duplicate vitepress config already defined in `baseConfig`
Non-breaking change.
/
Shortcuts in `package.json`, `.github` workflows, missing articles (so we can turn on deadlink detection) and custom hook for plugins ("typer") will be added/migrated in a separate PRs.
> feat: extract sidebar (DevHub) and cleanup config

- .github/scripts/docs-after-clone.sh
- .gitignore
- apps/docs/.vitepress/config.hub.ts
- apps/docs/.vitepress/config.ts
- apps/docs/.vitepress/data/composables.data.ts
- apps/docs/.vitepress/theme.hub.ts
- apps/docs/.vitepress/theme/components/ComposablesList.vue
- apps/docs/.vitepress/theme/index.ts
- apps/docs/.vitepress/theme/typer/cms-base-plugin.ts
- apps/docs/.vitepress/theme/typer/composables-builder.ts
- apps/docs/.vitepress/theme/typer/plugin.ts
- apps/docs/src/packages/composables/[composable].paths.ts
- apps/docs/src/packages/composables/index.md
- package.json
This PR is a continuation of https://github.com/shopware/frontends/pull/1313:
Docs-only change.
https://developer.shopware.com/frontends/packages/composables/#composables-list
> feat(docs): multi-context support

- .github/workflows/code-check.yml
ability to leverage pkg-pr-new, which will publish packages preview for PRs. More info: https://blog.stackblitz.com/posts/pkg-pr-new/
> feat: add pkg-pr-new to prepublish packages for testing

- apps/e2e-tests/page-objects/CategoryPage.ts
- apps/e2e-tests/tests/checkCategory.spec.ts
Fixes for flaky category tests 
Failed and flaky tests mainly concerned the sorting scenario
Before creating MR, I ran the tests locally about 80 times and had no further problems.
> fix(e2e): fix flaky category tests

- .husky/pre-commit
- apps/docs/src/getting-started/features/broadcasting.md
- apps/docs/src/getting-started/templates/custom-vue-project.md
- package.json
- packages/api-gen/README.md
- packages/cms-base/README.md
- packages/composables/README.md
- patches/automd.patch
- pnpm-lock.yaml
- scripts/generateAutomd.ts
- templates/astro/README.md
closes #1380
- updated `cms-base` package definition, as it's a nuxt layer, not nuxt module anymore
- created script `pnpm generateAutomd` to update all automd tags
- needed to create a patch for automd to trim files content
- automd `file` generations now have path relative to the repo, not to that file to improve refactoring and finding related files
> docs: automatically generate automd tags, update cms-base readme

- .changeset/calm-walls-wave.md
- examples/adyen-dropin-component/api-types/storeApiTypes.d.ts
- examples/b2b-quote-management/api-types/storeApiTypes.d.ts
- examples/commercial-customized-products/api-types/storeApiTypes.d.ts
- examples/commercial-quick-order/api-types/storeApiTypes.d.ts
- examples/express-checkout/api-types/storeApiTypes.d.ts
- examples/mollie-credit-card/api-types/storeApiTypes.d.ts
- packages/api-client/api-types/adminApiTypes.d.ts
- packages/api-client/api-types/storeApiTypes.d.ts
- packages/api-gen/src/commands/generate.ts
- packages/api-gen/src/mergingObjects.test.ts
- packages/api-gen/src/patchJsonSchema.test.ts
- packages/api-gen/src/patchJsonSchema.ts
- packages/api-gen/src/processAstSchemaAndOverrides.ts
- templates/vue-demo-store/api-types/storeApiTypes.d.ts
- improved error messages
- improved merging overrides
- sorting arrays, so always generated in the same order
- regenerated schema files
> fix(api-gen): error messages and merging patches

- .changeset/stale-files-learn.md
- packages/nuxt3-module/README.md
- packages/nuxt3-module/plugin.ts
- packages/nuxt3-module/src/index.ts
- templates/vue-demo-store/nuxt.config.ts
> feat: add API headers from config

- .changeset/six-snakes-joke.md
- examples/b2b-quote-management/vite.config.js
- examples/blank-playground/vite.config.js
- examples/commercial-quick-order/vite.config.ts
- examples/express-checkout/vite.config.js
- examples/login-form/vite.config.js
- examples/responsive-images/vite.config.js
- packages/composables/README.md
- packages/composables/build.config.ts
closes: #1426 
Bug fix (non-breaking change that fixes an issue) 
then we can take care of #1450
> fix(examples): configuration of vite

- .changeset/silent-cobras-sin.md
- packages/nuxt3-module/plugin.ts
This pull request replaces `createError` function with `showError` to redirect the user to the Nuxt error page to display maintenance info.
More context about why we should use `showError` function can be found here https://github.com/nuxt/nuxt/issues/15432
closes #1511
> fix(nuxt3-module): maintenance mode

- .changeset/angry-timers-hear.md
- packages/composables/src/useOrderDetails/useOrderDetails.test.ts
- packages/composables/src/useOrderDetails/useOrderDetails.ts
This pull request includes changes to the `useOrderDetails` composable to ensure that the last element is returned for the payment and shipping methods. This is because the backend returns collections sorted by the entry date. Additionally, new tests have been added to verify this behaviour.
🧰  Improvements to `useOrderDetails` composable:
* Updated `useOrderDetails` to return the last element for payment and shipping methods.
* Updated the type definitions to reflect the changes in the `useOrderDetails` composable.
🧪  Tests:
* Added tests to verify that the current payment and shipping methods are returned correctly.
* Added tests to handle cases where payment and shipping methods do not exist.
closes #1558
> fix(composables): shipping and payment method

- .changeset/calm-ligers-give.md
- .changeset/honest-crabs-march.md
- packages/composables/src/useCart/useCart.test.ts
- packages/composables/src/useCart/useCart.ts
- templates/vue-demo-store/i18n/de-DE/cart.json
- templates/vue-demo-store/i18n/en-GB/cart.json
- templates/vue-demo-store/i18n/pl-PL/cart.json
- templates/vue-demo-store/pages/checkout/cart.vue
- templates/vue-demo-store/pages/checkout/index.vue
This pull request fixes display shipping costs in the cart and checkout components. The changes include adding a `shippingCosts` property to the `useCart` composable, updating the cart and checkout components to display this information, and adding corresponding tests and translations.
* [`packages/composables/src/useCart/useCart.ts`](diffhunk://#diff-62200ee55ed613e59b385b7ec684bf93fc968a1b9e225cd5874c6f24ec7e73f3R69-R76): Added `shippingCosts` property to `UseCartReturn` type and implemented the logic to compute shipping costs. [[1]](diffhunk://#diff-62200ee55ed613e59b385b7ec684bf93fc968a1b9e225cd5874c6f24ec7e73f3R69-R76) [[2]](diffhunk://#diff-62200ee55ed613e59b385b7ec684bf93fc968a1b9e225cd5874c6f24ec7e73f3R248-R251) [[3]](diffhunk://#diff-62200ee55ed613e59b385b7ec684bf93fc968a1b9e225cd …
> fix(composables): add shipping costs

- .changeset/tidy-otters-know.md
- packages/api-client/api-gen.config.json
- packages/api-gen/README.md
- packages/api-gen/api-gen.schema.json
- packages/api-gen/src/cli.ts
- packages/api-gen/src/commands/generate.ts
- packages/api-gen/src/commands/validateJson.ts
- packages/api-gen/src/jsonOverrideUtils.ts
closes #1446 
Adds the possibility of multiple json overrides for schema
> feat(api-gen): allow multiple json overrides for schema

- .changeset/smart-mails-arrive.md
- packages/composables/README.md
- packages/composables/package.json
related #1406 
This PR marks package `@shopware-pwa/composables-next` as deprecated, further updates will be published under `@shopware/composables`
> chore: deprecate composables-next package for @shopware/composables

- apps/e2e-tests/tests/accessibilityCheck.spec.ts
Disable rules [page-has-heading-one](https://dequeuniversity.com/rules/axe/4.10/page-has-heading-one?application=RuleDescription), [heading-order](https://dequeuniversity.com/rules/axe/4.10/heading-order?application=RuleDescription) with know best practices issues.
> feat: disable axe core rules with known issues

- .changeset/famous-starfishes-enjoy.md
- templates/vue-demo-store/components/account/AccountOrder.vue
- templates/vue-demo-store/pages/checkout/index.vue
This pull request includes changes to the `vue-demo-store` project to add missing formatLink functionality for links in the checkout and my account pages.
Enhancements to link formatting:
* [`templates/vue-demo-store/components/account/AccountOrder.vue`](diffhunk://#diff-fa5775e0ab731d249361f7c1d64cd6f3ada97bcf61873bd971c6308d67b63bd1R14-R15): Introduced `formatLink` function and applied it to the order details links. [[1]](diffhunk://#diff-fa5775e0ab731d249361f7c1d64cd6f3ada97bcf61873bd971c6308d67b63bd1R14-R15) [[2]](diffhunk://#diff-fa5775e0ab731d249361f7c1d64cd6f3ada97bcf61873bd971c6308d67b63bd1L39-R41) [[3]](diffhunk://#diff-fa5775e0ab731d249361f7c1d64cd6f3ada97bcf61873bd971c6308d67b63bd1L48-R50)
* [`templates/vue-demo-store/pages/checkout/index.vue`](diffhunk://#diff-0bfd10dfff54f08af …
> fix(vue-demo): add missing formatLink function

- .changeset/lemon-chefs-count.md
- templates/vue-demo-store/app.vue
This pull request includes changes to set the `sw-language-id` header on the app context level for the `vue-demo-store` project. The main changes involve updating the `app.vue` file and creating a changeset file to document the patch.
- There is no need to watch language change because we are using force reload on language change
- Broadcasting will not change the language because we are setting it on the app context
Key changes:
* [`.changeset/lemon-chefs-count.md`](diffhunk://#diff-1af298846c2cf0aceefae0f2220df8c0bc5d6ad43711e06378b4a09949eac67bR1-R5): Added a changeset file to document the patch for setting the `sw-language-id` header on the app context level.
* [`templates/vue-demo-store/app.vue`](diffhunk://#diff-4359a385df4e4b0363f4e54f8cc7240a106ecfcf1be47ec09b91f7537990805fR105-R10 …
> fix: add global sw-language-id header

- .changeset/fluffy-ghosts-strive.md
- packages/cms-base-layer/components/public/cms/element/CmsBlockHtml.md
- packages/cms-base-layer/components/public/cms/element/CmsBlockHtml.vue
- packages/cms-base-layer/components/public/cms/element/CmsElementHtml.vue
- packages/composables/src/types/cmsBlockTypes.ts
- packages/composables/src/types/cmsElementTypes.ts
This pull request introduces a new component to render HTML blocks within the CMS base layer. The most important changes include the addition of the `CmsBlockHtml` component and its associated type definition.
New component addition:
* [`packages/cms-base-layer/components/public/cms/element/CmsBlockHtml.vue`](diffhunk://#diff-94ead15d1440828b87d91af295c9188a9abf4a47cec3980b5f10dd94a4f74382R1-R14): Implemented the `CmsBlockHtml` component to render a HTML section with appropriate styles and classes.
Type definition:
* [`packages/composables/src/types/cmsElementTypes.ts`](diffhunk://#diff-7bc8af787779a065a0f70856190939e3cde9f72c2bd6c01a2d5aacda8aa22957R48-R59): Added the `CmsBlockHtml` type definition to represent the structure of HTML blocks in the CMS.
closes #1528
> feat: add CmsBlockHtml and CmsElementHtml

- .changeset/modern-cows-cross.md
- packages/api-client/src/createAPIClient.ts
- packages/api-client/src/createApiClient.test.ts
After setting the content type in the api client headers like this:
```
headers: {
"Content-Type": "multipart/form-data", // <-- set this one
},
```
the actual content type is set to undefined. This fix ensures that the content type is removed in the API client and correctly set by the browser.
> fix: undefined content type in headers multipart/form-data

- apps/docs/.vitepress/theme/typer/cms-base-plugin.ts
- apps/docs/.vitepress/theme/typer/composables-builder.ts
- apps/docs/.vitepress/theme/typer/plugin.ts
- apps/docs/.vitepress/theme/typer/readme-loader.ts
closes: #1610 
from now on, the pages containing dynamically generated content will have:
```html
<div data-placeholder="dynamic-markdown"></div>
```
the `` is stripped out during minification process
> feat(docs): add tag for dynamically generated content

- .changeset/khaki-ideas-clean.md
- examples/b2b-employee-management/api-types/storeApiTypes.d.ts
- examples/b2b-quote-management/api-types/storeApiTypes.d.ts
- packages/api-gen/src/jsonOverrideUtils.ts
- packages/api-gen/src/mergeJsonOverrides.test.ts
closes #1746 
related to #1755 which still can be merged after slight adjustmets
Fixing problem with multiple overrides, when one of them is using object as types. In further work we should encourage only arrays
> fix(api-gen): merge json overrides

- apps/docs/.vitepress/theme/typer/readme-loader.ts
This PR removes markdown placeholder from non-transformed pages. Other plugins work fine, see https://github.com/shopware/frontends/pull/1808 .
> docs: remove dynamic markdown placeholder from non-transformed code

- .changeset/large-garlics-say.md
- packages/cms-base-layer/components/SwListingProductPrice.vue
This pull request addresses a bug fix in the `SwListingProductPrice.vue` file by correcting the usage of the wrong price component. The changes ensure that the correct component is used for displaying the price.
Bug fix:
* [`packages/cms-base-layer/components/SwListingProductPrice.vue`](diffhunk://#diff-338ccd6f8fa2a398ee28a6ef3d204276b322185419afcd22970e38d7ecc2fc60L82-R82): Replaced the incorrect `SharedPrice` component with the correct `SwSharedPrice` component for rendering the regulation price.
closes #1856
> fix: wrong price component

- templates/vue-demo-store/layouts/account.vue
The class attributes are missing for account page navigation items in the left side
Adding class attribute for making the icons visible in front-end
> fix: account missing attributes for icons

- .changeset/open-adults-rush.md
- packages/cms-base-layer/components/public/cms/section/CmsSectionSidebar.vue
This pr fixes the CmsSectionSidebar.vue when it's used on a landing page by removing useCategory and related code (otherwise we receive an error in the useCategory composable because there is no category available on a landing page)
> fix: remove category related code from CmsSectionSidebar

- .changeset/ten-numbers-tie.md
- packages/cms-base-layer/components/public/cms/block/CmsBlockTextTeaserSection.vue
- packages/cms-base-layer/components/public/cms/block/CmsBlockTextTwoColumn.vue
This update introduces responsiveness for the CMS blocks TextTeaserSection and TextTwoColumn. Previously, the columns would shrink on smaller screens but never stack. 
- The elements will now stack vertically from the `md` breakpoint, consistent with the behavior in the old storefront.
- Grid utilities are used for the layout change instead of flexbox to improve code readability.
- The `.container` class was removed in TextTeaserSection as it was constraining the block width.
Before:
After:
> fix(cms): cms text blocks responsiveness

- .changeset/lazy-deer-unite.md
- templates/vue-demo-store/app/components/account/AccountLoginForm.vue
* Login flow simplification:
* Removed the call to `refreshSessionContext` before invoking `login` in `AccountLoginForm.vue`, as it is no longer needed.
* Updated the emits definition and refactored related code for clarity and consistency in `AccountLoginForm.vue`. [[1]](diffhunk://#diff-1d94aa6bc24bdab65397d036cc8583da7b837227625ee561b944019b081e41faL7-L37) [[2]](diffhunk://#diff-1d94aa6bc24bdab65397d036cc8583da7b837227625ee561b944019b081e41faL48-R48)
> feat: remove refreshing session context before login

- packages/api-client/README.md
minor typo in code example fixed
> docs(api-client): hook registration syntax in README.md

- .husky/pre-commit
- package.json
- pnpm-workspace.yaml
Do not install packages right after release and allow npm registry to take it down before it hits the repo:
https://pnpm.io/settings#minimumreleaseage
> feat(security): set minimumReleaseAge for packages
