.github/workflows/code-check.yml, .github/workflows/e2e-tests.yml, package.json, turbo.json
create pipeline with GH actions
=> chore: enable actions full pipeline

.changeset/curvy-rockets-smash.md, .changeset/three-ads-rhyme.md, packages/api-client/src/index.ts, packages/api-client/src/services/NewsletterServiceTests/newsletterConfirmation.spec.ts, packages/api-client/src/services/formsService.ts, packages/api-client/src/services/newsletterService.ts, packages/composables/src/helpers/deepMerge.ts, packages/composables/src/useNewsletter.ts, templates/vue-demo-store/pages/account/index.vue, templates/vue-demo-store/pages/newsletter-subscribe.vue
=> feat: newsletter confirmation

.github/workflows/code-check.yml, .github/workflows/e2e-tests.yml, .github/workflows/publish-canary.yml, package.json, pnpm-lock.yaml
Updated pnpm to v8 with new lockfile structure: https://github.com/pnpm/pnpm/releases/tag/v8.0.0
=> feat: update repo to pnpm v8

.github/workflows/code-check.yml, .github/workflows/e2e-tests.yml, .github/workflows/publish-canary.yml, apps/docs/package.json, examples/example-builder/package.json, examples/express-checkout/package.json, package.json, packages/api-client/package.json, packages/cms-base/components.d.ts, packages/cms-base/components/public/cms/element/CmsElementBuyBox.vue, packages/cms-base/package.json, packages/composables/package.json, packages/eslint-config-shopware/package.json, packages/helpers/package.json, packages/nuxt3-module/package.json, packages/typer/package.json, packages/vue3-plugin/package.json, pnpm-lock.yaml, templates/vue-blank/package.json, templates/vue-demo-store/package.json, templates/vue-vite-blank/package.json
- improved cache of pnpm in actions
- updated dependencies
- added `audit` after build process to track potential problems
- added one exception for https://github.com/advisories/GHSA-p8p7-x288-28g6 - as not affected to this repo
=> chore: improve pnpm cache in gh actions

.changeset/weak-rules-wonder.md, templates/vue-demo-store/composables/useCmsHead.ts
fixes default value for `og:site_name`
=> fix(demo-template): open graph site name default value

.changeset/forty-peas-vanish.md, templates/vue-demo-store/.env.production, templates/vue-demo-store/README.md, templates/vue-demo-store/package.json
=> feat: nitro zero config 

.changeset/fair-hounds-watch.md, .changeset/funny-birds-juggle.md, .changeset/strong-swans-juggle.md, packages/cms-base/components/SwListingProductPrice.vue, packages/cms-base/components/public/cms/element/CmsElementBuyBox.vue, packages/types/shopware-6-client/models/checkout/cart/price/CalculatedPrice.d.ts, packages/types/shopware-6-client/models/content/product/Product.d.ts, packages/types/shopware-6-client/models/framework/pricing/Price.d.ts, templates/vue-demo-store/components/product/ProductPrice.vue
=> feat(cms-base): regulation price displaying

apps/docs/package.json, apps/e2e-tests/package.json, examples/example-builder/package.json, package.json, packages/api-client/package.json, packages/cms-base/package.json, packages/composables/package.json, packages/eslint-config-shopware/package.json, packages/helpers/package.json, packages/nuxt3-module/package.json, packages/typer/package.json, packages/vue3-plugin/package.json, pnpm-lock.yaml, templates/astro/package.json, templates/vue-blank/package.json, templates/vue-demo-store/package.json, templates/vue-vite-blank/package.json
Fixes: https://github.com/advisories/GHSA-7jxr-cg7f-gpgv
=> chore: bump dependencies

apps/e2e-tests/page-objects/HomePage.ts, apps/e2e-tests/page-objects/LoginPage.ts, apps/e2e-tests/page-objects/ProductPage.ts, apps/e2e-tests/page-objects/RegisterPage.ts, apps/e2e-tests/tests/createOrder.spec.ts, apps/e2e-tests/tests/login.spec.ts, apps/e2e-tests/tests/registrationUser.spec.ts
e2e tests fixes for flaky tests
=> fix: flaky e2e tests improvements

.changeset/clean-horses-know.md, .changeset/yellow-walls-attack.md, apps/docs/.vitepress/config.ts, packages/api-client/src/endpoints.ts, packages/typer/src/plugin-ts-function-description.ts
=> fix(typer,docs): replace removed label by custom tag

.changeset/lucky-meals-relate.md, packages/composables/src/useUser.ts, templates/vue-demo-store/components/account/AccountLoginForm.vue
=> fix(vue-demo-store): missing token on login

.changeset/happy-owls-deliver.md, templates/vue-demo-store/pages/account/payment.vue, templates/vue-demo-store/pages/checkout/index.vue, templates/vue-demo-store/pages/checkout/success/[id]/index.vue, templates/vue-vite-blank/src/components/Frontends.vue
fixes problem with proper payment method name in checkout
=> fix: payment method name

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yml
Updated the issue templates.
Just text changes.
=> chore: update issue templates

.changeset/strange-peaches-roll.md, apps/docs/src/packages/types.md
closes: #133 
Adding only a link to corresponding sub-repository files, containing all exported types.
Will be replaced with typegen in new API Client.
=> docs: link to types resources

apps/e2e-tests/page-objects/WishlistPage.ts
=> fix: e2e remove from wishlist

.changeset/khaki-flies-grow.md, templates/vue-demo-store/components/account/AccountChangePassword.vue, templates/vue-demo-store/components/account/AccountPersonalData.vue
=> fix: block editing data on update

packages/api-client/package.json, packages/helpers/package.json, packages/helpers/src/debounce.test.ts, packages/helpers/vitest.config.ts, pnpm-lock.yaml
...because we prefer for our Dom to be happy :P
Fixes issue with package lock file randomly changing because of jsdom/happy-dom dependencies
=> refactor: replace jsdom with happy-dom

templates/vue-demo-store/components/layout/LayoutHeader.vue, templates/vue-demo-store/components/layout/LayoutSideMenu.vue, templates/vue-demo-store/components/layout/LayoutStoreSearch.vue, templates/vue-demo-store/components/layout/LayoutTopNavigation.vue
improve head bar responsiveness
Before:
After:
Before: 
After:
Before:
After:
=> refactor: improve demo header responsiveness

templates/vue-demo-store/pages/search.vue
fixes not existing component invocation
=> fix: not existing loading icon in search page

.changeset/early-guests-dream.md, .changeset/hungry-bikes-smoke.md, apps/e2e-tests/page-objects/MyAccountPage.ts, packages/composables/src/useOrderDetails.ts, pnpm-lock.yaml, templates/astro/package.json, templates/vue-demo-store/app.vue, templates/vue-demo-store/components/account/AccountAddressCard.vue, templates/vue-demo-store/components/account/AccountAddressForm.vue, templates/vue-demo-store/components/account/AccountLoginForm.vue, templates/vue-demo-store/components/account/AccountMenu.vue, templates/vue-demo-store/components/checkout/CheckoutSideCart.vue, templates/vue-demo-store/components/layout/LayoutHeader.vue, templates/vue-demo-store/components/layout/LayoutSideMenu.vue, templates/vue-demo-store/components/layout/LayoutSidebar.vue, templates/vue-demo-store/components/layout/LayoutStoreSearch.vue, templates/vue-demo-store/components/shared/SharedModal.vue, templates/vue-demo-store/composables/useModal.ts, templates/vue-demo-store/layouts/account.vue, templates/vue-demo-store/layouts/checkout.vue, templates/vue-demo-store/layouts/default.vue, templates/vue-demo-store/pages/account/address.vue, templates/vue-demo-store/pages/checkout/index.vue
closes #64
- improved Modals with Teleport, related to #148 and #165
- added transitions for modals and sidebars
=> feat(demo): new modals strategy with useModal and Teleport

.github/workflows/lighthouse.yml, lighthouserc.js
closes [#103 ](https://github.com/shopware/frontends/issues/103)
=> feat: move lighthouse CI to github action

apps/docs/src/getting-started/templates/custom-project.md
Fix the link to content pages in documentation.
=> fix(docs): link to content pages

.changeset/heavy-bats-turn.md, packages/types/shopware-6-client/models/system/country/Country.d.ts, packages/types/shopware-6-client/models/system/country/CountryState.d.ts
closes: #161 
Adds some missing properties and internal types
=> feat(types): extend country and country state types

.changeset/fair-impalas-poke.md, packages/composables/src/useCart.ts
=> fix: isVirtualCart method

.changeset/loud-bulldogs-bake.md, .changeset/thirty-plums-sniff.md, .changeset/warm-squids-bathe.md, packages/api-client/src/services/ContextServiceTests/getAvailableShippingMethods.spec.ts, packages/api-client/src/services/contextService.ts, packages/composables/src/useCheckout.ts, templates/vue-demo-store/pages/checkout/index.vue
=> fix: shipping methods changes

.husky/pre-commit
Add's eslint check to pre-commit hook.
https://github.com/shopware/frontends/pull/175
=> feat: add pnpm run lint to pre-commit

lighthouserc.js
=> feat: lighthouse assertions adjustment

.changeset/lovely-drinks-love.md, .changeset/shy-bobcats-drive.md, packages/nuxt3-module/README.md, packages/nuxt3-module/build.config.ts, packages/nuxt3-module/package.json, packages/nuxt3-module/plugin.ts, packages/nuxt3-module/src/index.ts, packages/nuxt3-module/src/utils.ts, packages/nuxt3-module/tsconfig.json, pnpm-lock.yaml, templates/vue-blank/package.json, templates/vue-demo-store/package.json
closes: #160 
removes a requirement of installation extra api-client and composables-next which are available in the nuxt3-module dependency.
=> feat(nuxt3-module): deps improvements and documentation

.github/workflows/code-examples.yml
=> feat: add tests for stackblitz code examples

.changeset/slow-brooms-argue.md, templates/vue-demo-store/components/product/ProductCard.vue, templates/vue-demo-store/pages/search.vue
=> fix: add missing i18n composable

.changeset/good-comics-speak.md, .changeset/gorgeous-laws-invent.md, packages/composables/src/useSyncWishlist.ts, packages/composables/src/useWishlist.ts, templates/vue-demo-store/i18n/en-US/general.json, templates/vue-demo-store/i18n/pl-PL/general.json, templates/vue-demo-store/pages/wishlist.vue
=> fix: clear all items wishlist

.changeset/kind-candles-clap.md, templates/vue-demo-store/components/account/AccountOrderDownloads.vue
=> fix: getDocumentDate type

.github/workflows/e2e-tests.yml, apps/e2e-tests/playwright.config.ts
=> feat: add plywright report artifacts

templates/vue-demo-store/.stackblitzrc
related: #227 
- adds `NUXT_PUBLIC_SHOPWARE_DEV_STOREFRONT_URL` for stackblitz env for registering/langs purposes
=> feat(vue-demo-store): add .stackblitzrc with storefrontUrl env

templates/vue-demo-store/i18n/de-DE/checkout.json, templates/vue-demo-store/i18n/en-GB/checkout.json, templates/vue-demo-store/i18n/pl-PL/checkout.json, templates/vue-demo-store/pages/checkout/success/[id]/index.vue
closes:  #259
The translation was not working with object but with an array.
FYI: @mdanilowicz
=> fix(demo): order number success page

templates/vue-demo-store/components/layout/LayoutStoreSearch.vue
Closes https://github.com/shopware/frontends/issues/257
I removed the localPath from search route. I guess this will not be translated.
FYI @mdanilowicz.
=> fix(demo): suggest link

packages/composables/src/useSyncWishlist.ts
Reverts shopware/frontends#264
=> revert: "fix(demo): add missing getWishlistProducts"

packages/composables/src/useProductWishlist.ts, packages/composables/src/useSyncWishlist.ts
closes: #262
The main problem was that after removing a product from the wishlist the items were not updated. All other errors were consequential problems because of that also the wrong requests to the API when products were already deleted.
=> fix(demo): wishlist, move funciton calls

.changeset/nervous-gifts-help.md, packages/types/shopware-6-client/models/checkout/order/OrderLineItem.d.ts
=> fix(types): missing order item properties

.changeset/chatty-singers-buy.md, .changeset/odd-games-return.md, packages/composables/src/useAddress.ts, packages/composables/src/useSessionContext.ts, templates/vue-demo-store/components/account/AccountAddressCard.vue, templates/vue-demo-store/i18n/en-GB/account.json, templates/vue-demo-store/pages/checkout/index.vue
=> feat(vue-demo-store): edit address for guest customer

.changeset/eighty-spiders-divide.md, .changeset/purple-dodos-talk.md, packages/composables/src/useAddress.ts, packages/types/shopware-6-client/response/Error.d.ts, templates/vue-demo-store/components/account/AccountAddressForm.vue, templates/vue-demo-store/pages/account/address.vue
=> feat: add address error notification

.changeset/hungry-dancers-sell.md, templates/vue-demo-store/components/layout/LayoutStoreSearch.vue, templates/vue-demo-store/components/product/ProductSuggestSearch.vue, templates/vue-demo-store/pages/checkout/index.vue
=> feat(vue-demo): add missing data-testid

apps/docs/src/getting-started/e-commerce/prices.md, apps/docs/src/getting-started/routing.md, apps/docs/src/getting-started/templates/astro-template.md, apps/docs/src/getting-started/templates/blank-template.md, apps/docs/src/packages/helpers/getCategoryRoute.md, apps/docs/src/packages/helpers/getProductRoute.md, apps/docs/src/why-shopware-frontends.md, packages/helpers/src/category/getCategoryRoute.ts, packages/helpers/src/product/getProductRoute.ts
=> docs: omitting seo-url calls

.changeset/six-queens-hammer.md, packages/api-gen/build.config.ts, packages/api-gen/package.json, packages/api-gen/tsconfig.json, pnpm-lock.yaml
Fixes error for cli when command used
```sh
pnpx @shopware/api-gen generate
```
=> fix: cli building, not inlining prettier

.github/workflows/code-examples.yml
=> fix: change working directory for code examples

apps/e2e-tests/playwright.config.ts
=> feat(e2e): limit browsers list to chrome

.changeset/sixty-hornets-turn.md, packages/api-client-next/README.md, packages/api-client-next/src/errorInterceptor.test.ts, packages/api-client-next/src/errorInterceptor.ts, packages/api-client-next/src/index.ts, packages/api-client-next/src/invocations.e2e.test.ts
Thanks to community discussion: https://shopwarecommunity.slack.com/archives/C02TZE6UCJZ/p1689002187992129
Improved error handling for API client. Examples:
not catched error it still informative:
=> feat(api-client): improved error handling

.gitignore, apps/docs/src/framework/requirements.md
- Fixes a link
- Adds .idea folder to .gitignore (IDE inclusion :smile: )
=> fix(docs): link and add .idea to .gitignore

.changeset/strong-toes-add.md, .changeset/wild-bees-laugh.md, apps/docs/src/getting-started/languages.md, packages/composables/src/useInternationalization.ts, templates/vue-demo-store/app.vue, templates/vue-demo-store/components/account/AccountLoginForm.vue, templates/vue-demo-store/components/account/AccountMenu.vue, templates/vue-demo-store/components/checkout/CheckoutSideCart.vue, templates/vue-demo-store/components/errors/RoutingNotFound.vue, templates/vue-demo-store/components/layout/LayoutBreadcrumbs.vue, templates/vue-demo-store/components/layout/LayoutCheckoutHeader.vue, templates/vue-demo-store/components/layout/LayoutFooter.vue, templates/vue-demo-store/components/layout/LayoutHeader.vue, templates/vue-demo-store/components/layout/LayoutSideMenu.vue, templates/vue-demo-store/components/layout/LayoutStoreSearch.vue, templates/vue-demo-store/components/layout/LayoutTopNavigation.vue, templates/vue-demo-store/components/product/ProductCard.vue, templates/vue-demo-store/layouts/account.vue, templates/vue-demo-store/pages/account/index.vue, templates/vue-demo-store/pages/account/recover.vue, templates/vue-demo-store/pages/checkout/cart.vue, templates/vue-demo-store/pages/checkout/index.vue, templates/vue-demo-store/pages/checkout/success/[id]/unpaid.vue, templates/vue-demo-store/pages/error.vue, templates/vue-demo-store/pages/login.vue, templates/vue-demo-store/pages/reset-password.vue, templates/vue-demo-store/pages/wishlist.vue
=> feat: add new link builder

.changeset/cuddly-apricots-applaud.md, templates/vue-demo-store/components/account/AccountRegisterForm.vue
=> fix(vue-demo): revert SharedCountryStateInput

apps/e2e-tests/page-objects/ProductPage.ts, apps/e2e-tests/playwright.config.ts
closes [304](https://github.com/shopware/frontends/issues/304)
=> fix(e2e): solving problem with add to cart notification message

templates/vue-demo-store/components/layout/LayoutHeader.vue, templates/vue-demo-store/components/layout/LayoutSideMenu.vue
=> fix(demo): mobile view search and bg

apps/docs/src/getting-started/cms/overwriting-cms.md
=> fix(docs): improve example for cms overwrite

.changeset/dirty-buttons-clap.md, .changeset/gentle-bulldogs-warn.md, packages/cms-base/components/public/cms/element/CmsElementImage.vue, packages/composables/src/cms/useCmsElementImage.ts, packages/composables/src/helpers/urlIsAbsolute.spec.ts, packages/composables/src/helpers/urlIsAbsolute.ts
=> fix(cms): link building

apps/e2e-tests/page-objects/HomePage.ts, apps/e2e-tests/page-objects/WishlistPage.ts, apps/e2e-tests/tests/addToWishlist.spec.ts, apps/e2e-tests/tests/search.spec.ts
Adding e2e test for search functionality (search by suggested results case)
=> feat(e2e): test for search by suggest

.changeset/silly-pans-flash.md, templates/vue-demo-store/components/FrontendDetailPage.vue, templates/vue-demo-store/components/FrontendLandingPage.vue, templates/vue-demo-store/components/FrontendNavigationPage.vue, templates/vue-demo-store/layouts/default.vue, templates/vue-demo-store/pages/login.vue, templates/vue-demo-store/pages/reset-password.vue, templates/vue-demo-store/pages/search.vue, templates/vue-demo-store/pages/shopware.vue, templates/vue-demo-store/pages/wishlist.vue
=> feat(vue-demo): move breadcrumbs

apps/docs/src/packages/api-client.md
=> feat(docs): fix link to new api-client

.changeset/bright-suits-itch.md, packages/composables/src/useOrderDetails.ts
=> fix(composables): loadOrderDetails type

apps/docs/.vitepress/config.ts, apps/docs/src/framework/internal-structure.md, apps/docs/src/getting-started/templates/astro-template.md, apps/docs/src/getting-started/templates/blank-template.md, apps/docs/src/getting-started/templates/demo-store-template.md, apps/docs/src/resources/index.md, apps/docs/src/resources/troubleshooting.md
Improved some pages and removed confusing fork wording.
Added a troubleshooting page with first two common problems/hints.
=> feat(docs): clean up, add troubleshooting

apps/docs/src/framework/internal-structure.md
Change link target to overview building section.
=> feat(docs): change building section link

.changeset/clean-fans-end.md, templates/vue-demo-store/error.vue
=> fix: error page

.changeset/itchy-garlics-reflect.md, packages/composables/src/useSyncWishlist.ts
=> fix: catch wishlist items 404

.changeset/stupid-buses-try.md, packages/composables/src/useSessionContext.ts
closes: #376 (thanks to the fixed core issue)
=> fix(composables-next): access for the right active addresses

.changeset/tough-flies-joke.md, packages/helpers/src/category/getCategoryUrl.ts
=> fix(helpers-next): add leading slash for internal category links

.changeset/lucky-trains-share.md, packages/cms-base/components/public/cms/element/CmsElementText.vue
=> fix(cms-base): render inner img elements

.changeset/fresh-oranges-tell.md, templates/vue-demo-store/i18n/en-GB/account.json
=> fix(vue-demo): add missing translation

.changeset/smart-wombats-flow.md, packages/types/shopware-6-client/models/content/landing-page/LandingPage.d.ts
Add missing translated.url property for LandingPage.d.ts
=> fix: update LandingPage.d.ts with url

.changeset/tidy-kiwis-turn.md, packages/cms-base/helpers/buildUrlPrefix.ts, packages/cms-base/helpers/html-to-vue/getOptionsFromNode.ts, packages/cms-base/helpers/resolveUrl.ts
=> fix(cms): add category link resolver

.changeset/many-hotels-play.md, packages/cms-base/helpers/buildUrlPrefix.ts
=> fix(cms-base): url prefix builder

.changeset/popular-spies-raise.md, .github/workflows/check-pr-title.yml, packages/cms-base/components/public/cms/element/CmsElementImage.vue, packages/composables/src/cms/useCmsElementImage.ts
See also #440
Testing GitHub Action Issue :grin:
=> feat(cms-base): Improve CmsElementImage

.changeset/cool-seals-speak.md, packages/cms-base/components/SwProductCard.vue, packages/cms-base/components/public/cms/element/CmsElementProductListing.vue
=> fix(vue-demo-store): adjust styles

.changeset/curvy-games-unite.md, .changeset/plenty-dancers-live.md, packages/cms-base/components/public/cms/CmsPage.vue, packages/cms-base/components/public/cms/section/CmsSectionDefault.vue, packages/helpers/src/cms/getCmsLayoutConfiguration.ts
=> fix: css classes and visibility for CMS layout element

apps/docs/src/resources/troubleshooting.md
Add docs how to use https for localhost.
Docs update.
=> feat(docs): add hints to set up https

packages/cms-base/package.json, packages/composables/package.json
closes #473 
Fixes missing file in npm package
=> fix: missing file in exported package

packages/api-client-next/README.md
Just stumpled upon this looking at the npm packge reading your current discussion at https://github.com/shopware/frontends/discussions/471 🙂
=> fix: typo in api-client-next/README.md

apps/docs/src/resources/links.md
Update Links with new Blog Posts and Videos.
=> feat(docs): update links

pnpm-lock.yaml, templates/vue-vite-blank/.env.local, templates/vue-vite-blank/package.json, templates/vue-vite-blank/shopware.d.ts, templates/vue-vite-blank/src/App.vue, templates/vue-vite-blank/src/apiClient.ts, templates/vue-vite-blank/src/components/Frontends.vue, templates/vue-vite-blank/src/main.ts, templates/vue-vite-blank/tsconfig.json
Preview: https://stackblitz.com/github/shopware/frontends/tree/refactor--improve-vite-templatye/templates/vue-vite-blank?file=src%2Fmain.ts
updated vite project to show working for #482
=> refactor: vite template improvement

apps/e2e-tests/page-objects/SearchResultPage.ts
=> fix(e2e): add missing field

.changeset/mighty-cooks-relate.md, .changeset/old-cats-turn.md, packages/helpers/src/media/getMedia.ts, templates/vue-demo-store/components/account/AccountOrderLineItem.vue
=> fix(vue-demo): downloading digital products

examples/product-detail-page/package.json, examples/product-detail-page/src/apiClient.ts, examples/product-detail-page/src/components/ProductCard.vue, examples/product-detail-page/src/components/ProductView.vue, examples/product-detail-page/src/main.ts, pnpm-lock.yaml
Add new API to the PDP example
https://stackblitz.com/github/shopware/frontends/tree/feat/example-product-detail-page-api/examples/product-detail-page?file=README.md
=> feat(examples): example pdp new API

.changeset/few-beans-suffer.md, templates/vue-demo-store/composables/useCart.ts
=> fix(vue-demo): useCart example

apps/docs/src/getting-started/page-elements/images.md
=> feat(docs): fix broken link

examples/express-checkout/README.md
Change npm command to pnpm for express-checkout example to fix an error.
https://shopwarecommunity.slack.com/archives/C050L6NCMGQ/p1705406528524869
=> doc: fix npm command for express-checkout example

.changeset/gold-baboons-notice.md, packages/composables/src/useSessionContext.ts
=> fix(composables): countryID in session context

.github/workflows/check-pr-title.yml
As old action has been deprecated, new one should also work well on external contributions
=> ci: switch GH action for PR title check

packages/cms-base/components/public/cms/CmsPage.vue, templates/vue-demo-store/components/FrontendDetailPage.vue, templates/vue-demo-store/components/FrontendLandingPage.vue, templates/vue-demo-store/components/FrontendNavigationPage.vue, templates/vue-demo-store/components/account/AccountAddressCard.vue, templates/vue-demo-store/components/account/AccountOrder.vue, templates/vue-demo-store/components/checkout/CheckoutPromotionCode.vue, templates/vue-demo-store/components/layout/LayoutSideMenu.vue, templates/vue-demo-store/components/product/ProductAddToCart.vue, templates/vue-demo-store/components/product/ProductPrice.vue, templates/vue-demo-store/components/product/ProductSuggestSearch.vue, templates/vue-demo-store/components/product/ProductUnits.vue, templates/vue-demo-store/components/product/ProductVariantConfigurator.vue, templates/vue-demo-store/components/shared/SharedListingProductPrice.vue
Fixed type based deprications in the __vue-demo-store__ by using `import type { Schemas } from "#shopware"`.
=> fix(vue-demo-store): type deprications in vue-demo-store

packages/api-gen/src/cli.ts, packages/api-gen/src/commands/generate.ts, packages/api-gen/src/patches.ts
Small improvement for quicker schema generation
=> perf(api-gen): small improvements for schema generator to avoid unnceessary IO operations

apps/e2e-tests/tests/checkStackblitzTemplates.spec.ts
Small fixes for stackblitz template tests 
- increasing the timout time for the test
- slight change in flow test
=> fix(e2e): stackblitz template tests fixes

.changeset/curvy-mice-give.md, packages/composables/src/useCheckout.ts
Fix loading only available shipping methods
=> fix(composables): available shipping methods

.github/dependabot.yml, package.json, pnpm-lock.yaml
audit fail and ignores for dependabot
=> chore: fix audit fail

.changeset/tall-mice-pump.md, packages/helpers/README.md, packages/helpers/src/cms/getCmsLayoutConfiguration.ts, packages/helpers/src/cms/index.ts, packages/helpers/src/cms/layoutClasses.ts, packages/helpers/src/index.test.ts, templates/vue-demo-store/uno.config.ts
=> feat(helpers): export helpers css classes

.changeset/nasty-zebras-compete.md, packages/cms-base/components/SwListingProductPrice.vue, packages/composables/src/mocks/Product.ts, packages/composables/src/useProductPrice.spec.ts, packages/composables/src/useProductPrice.ts, templates/vue-demo-store/components/product/ProductPrice.vue, templates/vue-demo-store/i18n/de-DE/product.json, templates/vue-demo-store/i18n/en-GB/product.json
=> feat(vue-demo): add regulation price

.changeset/thin-hats-return.md, examples/adyen-dropin-component/nuxt.config.ts, examples/modal-teleport/nuxt.config.ts, examples/mollie-credit-card/playground/nuxt.config.ts, examples/snippets-middleware/nuxt.config.ts, packages/cms-base/nuxt.config.ts, packages/composables/nuxt.config.ts, templates/vue-blank/nuxt.config.ts, templates/vue-demo-store/nuxt.config.ts
=> fix: turn off Nuxt telemetry

.github/dependabot.yml, .github/workflows/code-examples.yml, apps/e2e-tests/examples.config.ts, apps/e2e-tests/tests/checkCodeExamples.spec.ts, apps/e2e-tests/tests/pages/blank.html, examples/README.md, examples/adyen-dropin-component/app.vue, examples/blank-playground/src/App.vue, examples/commercial-customized-products/src/App.vue, examples/commercial-quick-order/src/App.vue, examples/example-builder/src/App.vue, examples/express-checkout/src/App.vue, examples/login-form/src/App.vue, examples/modal-teleport/app.vue, examples/modal-teleport/nuxt.config.ts, examples/modal-teleport/pages/index.vue, examples/mollie-credit-card/playground/app.vue, examples/new-api-client/src/App.vue, examples/product-detail-page/src/App.vue, examples/responsive-images/src/App.vue, examples/snippets-middleware/app.vue, examples/use-add-to-cart/src/App.vue, examples/use-cart/src/App.vue, examples/use-checkout/src/App.vue
[README](https://github.com/shopware/frontends/pull/679/files?short_path=49aaa28#diff-49aaa2819e35a856818ecec8c9fa7e1c79ad028d3f44bd749736353cfb51bac9) for examples dir added
the e2e testing mechanism tailored for our mini projects placed in `./examples` dir:
- it opens every project using stackblitz
- waits for project to be built and run in preview iframe
- checks if preview iframe contains a common div with specified test-id
- test fails if the project can't be loaded and displayed a HTML with a special container (like http 500, 404)  
=> test(examples): improve e2e for code examples availability

.changeset/sweet-flowers-dance.md, packages/composables/src/useAddress.ts
=> fix(composables): edit user address

apps/e2e-tests/tests/checkCodeExamples.spec.ts
Small fixes for code example tests : 
- add README.md to ignore 
- choosing the correct branch to run tests
=> fix(e2e): fixes for code examples tests

.changeset/sour-days-repair.md, apps/docs/.vitepress/config.ts, apps/docs/src/getting-started/b2b/index.md, apps/docs/src/getting-started/b2b/quote-management.md
=> feat(docs): b2b quote management

apps/docs/src/resources/troubleshooting.md
=> feat(docs): add proxy

.changeset/nine-squids-share.md, apps/docs/src/getting-started/templates/blank-template.md, apps/docs/src/getting-started/templates/demo-store-template.md, apps/docs/src/packages/api-client/docs/storefront-url.md, examples/adyen-dropin-component/README.md, examples/adyen-dropin-component/nuxt.config.ts, examples/mollie-credit-card/playground/nuxt.config.ts, examples/snippets-middleware/nuxt.config.ts, packages/nuxt3-module/README.md, packages/nuxt3-module/package.json, packages/nuxt3-module/src/index.ts, packages/nuxt3-module/src/utils.ts, pnpm-lock.yaml, templates/vue-blank/nuxt.config.ts, templates/vue-demo-store/nuxt.config.ts
closes: #702 
New feature (non-breaking change which adds functionality)
=> feat(nuxt3-module): add deprecation message and use global module config

packages/nuxt3-module/plugin.ts, packages/nuxt3-module/src/index.ts
Feature as [described in docs](https://frontends.shopware.com/getting-started/templates/custom-vue-project.html#shopware-endpoint-on-the-ssr-mode) was commented out in line 69-71
Bug fix (non-breaking change that fixes an issue) 
New feature (non-breaking change which adds functionality) 
(Re-enabled old feature #325)
=> fix(nuxt3-module): re-enabled SSR endpoint feature

package.json, pnpm-lock.yaml
=> chore: audit issue bump

.changeset/few-rice-leave.md, packages/cms-base/components/SwProductCard.vue
=> fix: block double click on the wishlist button

apps/docs/src/getting-started/features/custom-products.md
=> docs: use correct links for customized products section

templates/vue-demo-store/components/account/AccountOrderDetails.vue, templates/vue-demo-store/components/account/AccountOrderSummary.vue, templates/vue-demo-store/pages/account/order.vue
closes: #781 
Bug fix (non-breaking change that fixes an issue) 
This problem was related to new API Client changes.
=> fix(demo-store): account order summary

examples/b2b-quote-management/src/App.vue
fixes https://github.com/shopware/frontends/actions/runs/8627308458
=> fix(examples): add required container for e2e purposes

.changeset/smart-balloons-look.md, packages/api-gen/src/commands/generate.ts
=> feat(api-gen): blob type support

.changeset/young-files-laugh.md, packages/cms-base/components/public/cms/element/CmsElementImageGallery.vue, packages/cms-base/components/public/cms/element/CmsElementImageGallery3dPlaceholder.vue
Moved the svg 3d media placeholder to the vue component
=> fix(cms): 3d placeholder vue component

templates/vue-demo-store/components/listing-filters/ListingFiltersPrice.vue, templates/vue-demo-store/pages/search.vue
The price filter was not applied to the search request correctly.
The price filter from the route was not passed through the input fields (after hard reload).
The issue was reported [here](https://shopwarecommunity.slack.com/archives/C050L6NCMGQ/p1715936468002169).
=> fix: price filter on search page

.changeset/wet-lions-decide.md, examples/responsive-images/package.json, packages/api-client-next/src/errorInterceptor.ts, packages/composables/src/index.ts, packages/composables/src/useAddress.ts, packages/composables/src/useCartItem.ts, packages/composables/src/useCustomerPassword.test.ts, packages/composables/src/useCustomerPassword.ts, pnpm-lock.yaml, templates/vue-demo-store/components/account/AccountChangePassword.vue, templates/vue-demo-store/components/account/AccountMenu.vue, templates/vue-demo-store/components/account/AccountRecoverPassword.vue, templates/vue-demo-store/pages/checkout/index.vue, templates/vue-demo-store/pages/login.vue
Part of #941
Breaking the API of `useCustomerPassword` for consistency in error handling.
Breaking change
=> refactor!: change useCustomerPassword error handling

examples/adyen-dropin-component/api-types/storeApiTypes.d.ts, examples/b2b-quote-management/api-types/storeApiTypes.d.ts, examples/commercial-customized-products/api-types/storeApiTypes.d.ts, examples/commercial-quick-order/api-types/storeApiTypes.d.ts, examples/express-checkout/api-types/storeApiTypes.d.ts, examples/mollie-credit-card/api-types/storeApiTypes.d.ts, packages/api-client-next/api-types/storeApiTypes.d.ts, packages/api-client-next/api-types/storeApiTypes.overrides.ts, packages/composables/src/useListing.ts, packages/composables/src/useProductConfigurator.ts, packages/composables/src/useProductPrice.ts, templates/vue-demo-store/api-types/storeApiTypes.d.ts, templates/vue-demo-store/composables/useCmsHead.ts, templates/vue-demo-store/pages/account/order.vue, templates/vue-demo-store/pages/search.vue
Updated overrides to new schema from 6.6.3.0.
This reduces the number of minimal TODOs on API schema from over a 100 to **53**
Still work to do but we're getting there!
=> feat(api-client): updated types overrides for 6.6.3.0

.changeset/big-plums-hunt.md, packages/composables/src/useAddress.ts, packages/composables/src/useB2bQuoteManagement.ts, packages/composables/src/useCart.ts, packages/composables/src/useCartItem.ts, packages/composables/src/useCountries.ts, packages/composables/src/useNewsletter.ts, packages/composables/src/useOrderDetails.ts, packages/composables/src/useOrderPayment.ts, packages/composables/src/useProductReviews.ts, packages/composables/src/useSalutations.ts, packages/composables/src/useUser.ts
closes #941 
Most of the methods return now the data from API, even if storing data locally as well. Error handling now more consistent and predictable.
=> refactor(composables): return data from the API in most of the methods

examples/adyen-dropin-component/api-types/storeApiTypes.d.ts, examples/b2b-quote-management/api-types/storeApiTypes.d.ts, examples/commercial-customized-products/api-types/storeApiTypes.d.ts, examples/commercial-quick-order/api-types/storeApiTypes.d.ts, examples/express-checkout/api-types/storeApiTypes.d.ts, examples/mollie-credit-card/api-types/storeApiTypes.d.ts, packages/api-client-next/api-types/storeApiTypes.d.ts, packages/api-client-next/api-types/storeApiTypes.overrides.ts, packages/api-client/src/services/contextService.ts, packages/api-gen/src/commands/generate.ts, templates/vue-demo-store/api-types/storeApiTypes.d.ts
fix the generation of admin types adds some new todos to open api
=> fix: use proper default admin api schema and fix some types

examples/adyen-dropin-component/package.json, examples/amazon-pay-button-example/package.json, examples/modal-teleport/package.json, examples/mollie-credit-card/package.json, examples/snippets-middleware/package.json, examples/use-add-to-cart/package.json, examples/use-cart/package.json, examples/use-checkout/package.json, packages/cms-base/package.json, packages/composables/package.json, packages/nuxt3-module/package.json, pnpm-lock.yaml, templates/vue-blank/package.json, templates/vue-demo-store/package.json
Reverted nuxt upgrade as it's causing problems with layouts
=> fix: revert nuxt to 3.11.2 as 3.12 is breaking layouts

apps/e2e-tests/playwright.config.ts, apps/e2e-tests/tests/checkSearch.spec.ts
Stop opening html report and skip test for filters on search page
=> chore: stop opening html report

apps/e2e-tests/tests/checkCodeExamples.spec.ts
the example cannot run on stackblitz because the module is out of context a stackblitz runtime (../src/module).
=> fix(examples): ignore amazon pay due to out of context module

apps/docs/src/getting-started/features/broadcasting.md, examples/adyen-dropin-component/api-types/storeApiTypes.d.ts, examples/b2b-quote-management/api-types/storeApiTypes.d.ts, examples/commercial-customized-products/api-types/storeApiTypes.d.ts, examples/commercial-quick-order/api-types/storeApiTypes.d.ts, examples/express-checkout/api-types/storeApiTypes.d.ts, examples/mollie-credit-card/api-types/storeApiTypes.d.ts, packages/api-client-next/api-types/storeApiSchema.overrides.json, packages/api-client-next/api-types/storeApiTypes.d.ts, packages/api-client-next/api-types/storeApiTypes.overrides.ts, packages/api-client-next/src/createAPIClient.ts, packages/composables/src/useCartItem.test.ts, packages/composables/src/useCartItem.ts, packages/composables/src/useSessionContext.ts, templates/vue-demo-store/api-types/storeApiTypes.d.ts, templates/vue-demo-store/app.vue, templates/vue-demo-store/components/account/AccountMenu.vue, templates/vue-demo-store/composables/useBroadcastConsumer.ts, templates/vue-demo-store/layouts/account.vue, templates/vue-demo-store/nuxt.config.ts
addition to #866 
Refactor to simplify workflow with channels:
- login in a single composable
- reliable data sync - listening to apiClient responses and setting up data so it's always fresh
- sync cart changes, login, logout etc
https://github.com/shopware/frontends/assets/13100280/8f4596ef-0867-49f7-bb12-6649dbf6cfc2
=> chore: refactor broadcasting

.changeset/nice-balloons-give.md, packages/cms-base/components/public/cms/element/CmsElementCrossSelling.vue, packages/composables/src/types/cmsElementTypes.ts, templates/vue-demo-store/components/product/ProductCard.vue
Move width property as a static value
closes #974
=> feat(cms): cross sell slider

apps/docs/.vitepress/theme/custom.css
Fixes a position for anchors related to headers in .md
=> fix(docs): header anchors

apps/docs/.vitepress/config.ts, apps/docs/.vitepress/navigation.ts, apps/docs/src/framework/internal-structure.md, apps/docs/src/framework/shopping-experiences.md, apps/docs/src/framework/styling.md, apps/docs/src/getting-started/cms/content-pages.md, apps/docs/src/getting-started/cms/index.md, apps/docs/src/getting-started/cms/multiple-cms.md, apps/docs/src/getting-started/e-commerce/prices.md, apps/docs/src/getting-started/features/custom-products.md, apps/docs/src/getting-started/page-elements/breadcrumbs.md, apps/docs/src/getting-started/page-elements/examples/footer-navigation/index.md, apps/docs/src/getting-started/page-elements/examples/product-detail-page/index.md, apps/docs/src/getting-started/page-elements/images.md, apps/docs/src/getting-started/routing.md, apps/docs/src/getting-started/templates/demo-store-template.md, apps/docs/src/installation.md, apps/docs/src/resources/integrations/cms/index.md, apps/docs/src/resources/integrations/cms/storyblok.md, apps/docs/src/resources/integrations/cms/strapi.md, apps/docs/src/resources/integrations/commercial/b2b-quote-management.md, apps/docs/src/resources/integrations/commercial/index.md, apps/docs/src/resources/integrations/payments/index.md, examples/adyen-dropin-component/README.md
Fixing more 404 Errors. Because it is a joy.
=> fix(docs): 404 pages second iteration

apps/docs/src/getting-started/cms/multiple-cms.md, templates/vue-demo-store/components/account/AccountRegisterForm.vue, templates/vue-demo-store/components/layout/LayoutStoreSearch.vue, templates/vue-demo-store/composables/useAuthGuard.ts, templates/vue-demo-store/pages/[...all].vue, templates/vue-demo-store/pages/login.vue
`process.client` is deprecated we should now use `import.meta.client`.
=> feat: use import.meta.client

examples/adyen-dropin-component/package.json, examples/amazon-pay-button-example/package.json, examples/amazon-pay-button-example/playground/package.json, examples/modal-teleport/package.json, examples/mollie-credit-card/package.json, examples/snippets-middleware/package.json, examples/use-add-to-cart/package.json, examples/use-cart/package.json, examples/use-checkout/package.json, packages/cms-base/package.json, packages/composables/package.json, packages/nuxt3-module/package.json, pnpm-lock.yaml, templates/vue-blank/package.json, templates/vue-demo-store/package.json
closes #1106
for some reason, the new Nuxt version is making the whole page unclickable with a nondeterministic hydration error.
We'll revert for now and check when the new release will come up.
=> chore: downgrade nuxt

.github/dependabot.yml, apps/docs/package.json, apps/e2e-tests/package.json, examples/b2b-quote-management/package.json, examples/modal-teleport/package.json, package.json, packages/api-client/package.json, packages/api-gen/package.json, packages/cms-base/package.json, packages/eslint-config-shopware/package.json, pnpm-lock.yaml
bump dependencies and update dependabot config to better group dependencies. Also limit number of active PRs to reduce CI usage time.
=> chore: bump dependencies and adjust dependabot

.changeset/orange-schools-relax.md, templates/vue-demo-store/pages/account/order.vue, templates/vue-demo-store/pages/wishlist.vue
closes: #1146 and fixes the same issue but in account order's list
=> fix: use actual component for wishlist and orders pagination in vue-demo-store

templates/vue-demo-store/components/account/AccountLoginForm.vue
=> fix(vue-demo-store): typo in AccountLoginForm.vue

.changeset/happy-timers-cross.md, .changeset/mean-wolves-hope.md, packages/cms-base/components/SwProductCard.vue, packages/cms-base/components/SwProductPrice.vue, packages/cms-base/components/public/cms/element/CmsElementBuyBox.vue, templates/vue-demo-store/components/product/ProductCard.vue
- Change resizing mode of Shopware CDN from `crop` to `cover` mode for image of product within `SwProductCart` component
- Make translation for tier pricing table consistent
=> fix(cms-base): consistent translations and changed resizing mode for product images

.changeset/small-ears-grin.md, packages/cms-base/components/public/cms/element/CmsElementProductListing.vue, templates/vue-demo-store/components/account/AccountOrderDetails.vue, templates/vue-demo-store/pages/account/order.vue, templates/vue-demo-store/pages/wishlist.vue
Add data-testid for wishlist limit box
closes #1158
=> feat(vue-demo): add wishlist data-testid

packages/composables/src/types/cmsElementTypes.ts
fixes missing config file in image type
=> fix(types): add horizontalAlign in imageElementConfig

pnpm-lock.yaml, templates/vue-demo-store/package.json
closes: #1198
can be tested if solves the problem by `npx tiged shopware/frontends/templates/vue-demo-store#fix/remove-old-dependency` <- tiged for specific branch
=> fix(templates): remove unused dependency from vue-demo-store

.changeset/few-melons-remember.md, apps/docs/.vitepress/theme/typer/cms-base-plugin.ts, packages/cms-base/components/public/cms/element/CmsElementBuyBox.md, packages/cms-base/components/public/cms/element/CmsElementCategoryNavigation.md, packages/cms-base/components/public/cms/element/CmsElementCrossSelling.md, packages/cms-base/components/public/cms/element/CmsElementCustomForm.md, packages/cms-base/components/public/cms/element/CmsElementForm.md, packages/cms-base/components/public/cms/element/CmsElementImage.md, packages/cms-base/components/public/cms/element/CmsElementImageGallery.md, packages/cms-base/components/public/cms/element/CmsElementImageSlider.md, packages/cms-base/components/public/cms/element/CmsElementManufacturerLogo.md, packages/cms-base/components/public/cms/element/CmsElementProductBox.md, packages/cms-base/components/public/cms/element/CmsElementProductDescriptionReviews.md, packages/cms-base/components/public/cms/element/CmsElementProductListing.md, packages/cms-base/components/public/cms/element/CmsElementProductName.md, packages/cms-base/components/public/cms/element/CmsElementProductSlider.md, packages/cms-base/components/public/cms/element/CmsElementSidebarFilter.md, packages/cms-base/components/public/cms/element/CmsElementText.md, packages/cms-base/components/public/cms/element/CmsElementVimeoVideo.md, packages/cms-base/components/public/cms/element/CmsElementYoutubeVideo.md
Adding an info about exported components for Cms Elements resolving. It's used in the docs (see the attached screen).
part of: #1073
New feature (non-breaking change which adds functionality)
=> docs(cms-base): brief info about cms elements

.changeset/wise-cheetahs-remember.md, templates/vue-demo-store/i18n/de-DE/errors.json, templates/vue-demo-store/i18n/en-GB/errors.json, templates/vue-demo-store/i18n/pl-PL/errors.json
Fixed `promotion-not-found` error message
closes #1166
=> fix(vue-demo): promotion code error message

.changeset/young-insects-hug.md, packages/cms-base/components/public/cms/element/CmsElementText.vue
closes: #1263 
to not directly render the child vnodes 
working preview of the same solution: https://stackblitz.com/edit/github-94vefp?file=error.vue
=> fix(cms-base): render function for CmsElementText

apps/docs/.vitepress/theme/components/ComposablesList.vue
=> feat(docs): change link structure for seo bots

.changeset/funny-parents-kiss.md, examples/commercial-quick-order/src/App.vue, examples/modal-teleport/components/AppModal.vue, packages/cms-base/components/SwProductCard.vue, packages/cms-base/components/SwProductListingFilters.vue, packages/cms-base/components/SwSlider.vue, packages/cms-base/components/public/cms/element/CmsElementCrossSelling.vue, packages/cms-base/components/public/cms/element/CmsElementImage.vue, packages/cms-base/components/public/cms/element/CmsElementImageGallery.vue, packages/cms-base/components/public/cms/element/CmsElementProductSlider.vue, templates/vue-demo-store/components/account/AccountAddressForm.vue, templates/vue-demo-store/components/account/AccountLoginForm.vue, templates/vue-demo-store/components/account/AccountMenu.vue, templates/vue-demo-store/components/account/AccountRegisterForm.vue, templates/vue-demo-store/components/layout/LayoutSidebar.vue, templates/vue-demo-store/components/layout/LayoutStoreSearch.vue, templates/vue-demo-store/components/product/ProductCard.vue, templates/vue-demo-store/components/product/ProductSuggestSearch.vue, templates/vue-demo-store/components/shared/SharedAccountAddressForm.vue, templates/vue-demo-store/components/shared/SharedCountryStateInput.vue, templates/vue-demo-store/components/shared/SharedModal.vue, templates/vue-demo-store/pages/checkout/index.vue, templates/vue-demo-store/pages/search.vue
updates to templateRef from Vue 3.5 https://blog.vuejs.org/posts/vue-3-5#usetemplateref
=> feat: update to templateRefs and improve types

.changeset/tall-owls-jam.md, packages/api-gen/src/commands/generate.ts, packages/api-gen/src/commands/loadSchema.ts
Fixes an import [pitfall](https://github.com/dotenv-org/examples/tree/master/usage/dotenv-es6-import).
=> fix(api-gen): dotenv import

apps/docs/src/getting-started/templates/blank-template.md, apps/docs/src/getting-started/templates/demo-store-template.md, apps/docs/src/installation.md, packages/nuxt3-module/plugin.ts, packages/nuxt3-module/src/index.ts
=> fix: add missing ssr endpoint

apps/docs/.vitepress/config.ts, apps/docs/src/resources/community-modules/index.md, apps/docs/src/resources/integrations/index.md, apps/docs/src/resources/links.md, apps/docs/src/resources/troubleshooting.md
Minor changes and updates to docs.
=> docs: update links and community modules

.changeset/rare-dancers-talk.md, packages/api-client/api-types/adminApiSchema.overrides.json, packages/api-client/api-types/adminApiTypes.d.ts
closes: #1117
the change in `overrides.json` file will be reverted once the openapi schema is fixed on  `shopware/shopware` core repository
=> feat(api-client): extend admin api types

.changeset/big-dingos-battle.md, apps/docs/src/getting-started/features/broadcasting.md, apps/docs/src/resources/troubleshooting.md, templates/vue-demo-store/app.vue, templates/vue-demo-store/nuxt.config.ts
Disable broadcasting for the Vue demo template
closes #767
=> feat(vue-demo): disable broadcasting

.changeset/eighty-emus-dance.md, .changeset/wicked-eyes-divide.md, examples/adyen-dropin-component/api-types/storeApiTypes.d.ts, examples/b2b-quote-management/api-types/storeApiTypes.d.ts, examples/commercial-customized-products/api-types/storeApiTypes.d.ts, examples/commercial-customized-products/package.json, examples/commercial-quick-order/api-types/storeApiTypes.d.ts, examples/express-checkout/api-types/storeApiTypes.d.ts, examples/mollie-credit-card/api-types/storeApiTypes.d.ts, packages/api-client/api-types/storeApiSchema.json, packages/api-client/api-types/storeApiTypes.d.ts, packages/api-gen/tests/api-types/testSchema.json, packages/composables/src/useCartItem/useCartItem.ts, packages/composables/src/useNewsletter/useNewsletter.ts, templates/vue-demo-store/api-types/storeApiTypes.d.ts
=> feat: update schema

apps/docs/src/getting-started/templates/demo-store-template.md, apps/docs/src/resources/links.md, apps/docs/src/resources/troubleshooting.md
Minor improvements for the Docs.
=> docs: update links, troubleshooting, setup

packages/api-client/README.md, packages/api-gen/README.md, packages/cms-base/README.md, packages/composables/README.md, packages/nuxt3-module/README.md
adds links to the api-client tutorial.
=> docs: update README files in terms of API Client tutorial and fix slack channel name

.readme/vercel.svg, README.md, templates/vue-demo-store/README.md
Added a quick deploy button from Vercel for vue-demo-store template and in the main README
vue-demo-store readme
main readme
=> docs: add deploy with vercel buttons

.changeset/clean-glasses-jog.md, .changeset/olive-pandas-draw.md, examples/adyen-dropin-component/api-types/storeApiTypes.d.ts, examples/b2b-quote-management/api-types/storeApiTypes.d.ts, examples/commercial-customized-products/api-types/storeApiTypes.d.ts, examples/commercial-quick-order/api-types/storeApiTypes.d.ts, examples/express-checkout/api-types/storeApiTypes.d.ts, examples/mollie-credit-card/api-types/storeApiTypes.d.ts, packages/api-client/api-types/adminApiSchema.overrides.json, packages/api-client/api-types/adminApiTypes.d.ts, packages/api-client/api-types/storeApiSchema.json, packages/api-client/api-types/storeApiSchema.overrides.json, packages/api-client/api-types/storeApiTypes.d.ts, packages/api-gen/src/apiClient.ts, packages/api-gen/src/commands/loadSchema.ts, packages/api-gen/src/commands/validateJson.ts, packages/cms-base/components/SwProductReviews.vue, templates/vue-demo-store/api-types/storeApiTypes.d.ts, templates/vue-demo-store/components/account/AccountOrderDownloads.vue, templates/vue-demo-store/components/product/ProductReviews.vue, turbo.json
This feature adds a check to validate the endpoints exposed by the API against the endpoints defined in the OpenAPI json schema.
The result contains errors description and the summary. Current summaries for the Store API:
Admin API:
(example gitlab merge request 2389)
To validate the Store API
```bash
npx https://pkg.pr.new/shopware/frontends/@shopware/api-gen@1365 loadSchema --apiType=store --filename=storeApiSchema.json
npx https://pkg.pr.new/shopware/frontends/@shopware/api-gen@1365 validateJson --apiType=store
npm i -g @redocly/cli@latest
redocly lint --skip-rule operation-4xx-response --skip-rule no-server-example.com --skip-rule no-unused-components ./api-types/storeApiSchema.json
```
To validate the Admin API
```bash
npx https://pkg.pr.new/shopware/frontends/@shopware/api-gen@1365 …
```
=> feat(api-gen): validate exposed endpoints vs schema defined endpoints

apps/e2e-tests/tests/checkCodeExamples.spec.ts
Until the problem with cloning the repo in stackblitz is solved, we add the api-client-tutorial example to the ignor so that the examples checks end successfull
=> fix(e2e): temporary ignore api client tutorial from e2e check

.changeset/proud-swans-breathe.md, packages/types/README.md, packages/types/package.json
part of #1406 deprecating old types package
=> chore: depretating types package

apps/e2e-tests/package.json, apps/e2e-tests/tests/addProductReview.spec.ts, apps/e2e-tests/tests/addToCart.spec.ts, apps/e2e-tests/tests/addToWishlist.spec.ts, apps/e2e-tests/tests/checkCategory.spec.ts, apps/e2e-tests/tests/checkCodeExamples.spec.ts, apps/e2e-tests/tests/checkForSeoUrl.spec.ts, apps/e2e-tests/tests/checkProductVariants.spec.ts, apps/e2e-tests/tests/checkSearch.spec.ts, apps/e2e-tests/tests/checkStackblitzTemplates.spec.ts, apps/e2e-tests/tests/createOrder.spec.ts, apps/e2e-tests/tests/login.spec.ts, apps/e2e-tests/tests/myAccountTests.spec.ts, apps/e2e-tests/tests/registrationUser.spec.ts, apps/e2e-tests/tests/search.spec.ts
Adding tags to tests (@vue-demo-store, @stackblitz, in another PR the @accessibility tag will be added). Thanks to this, you will be able to run test scenarios depending on your needs.
=> feat(e2e): add tags for playwright tests

packages/api-gen/src/commands/loadSchema.ts
Fixes small typo in loadSchema.
Don't think anyone really ran into problems with this, since the commands expects the base url anyway.
Typo fixed
None
=> chore: fix api-gen typo

.changeset/unlucky-dogs-help.md, packages/composables/src/useCustomerOrders/useCustomerOrders.ts, packages/composables/src/useDefaultOrderAssociations/useDefaultOrderAssociations.test.ts, packages/composables/src/useDefaultOrderAssociations/useDefaultOrderAssociations.ts, packages/composables/src/useOrderDetails/useOrderDetails.ts, templates/vue-demo-store/pages/account/order.vue
=> fix(composables): add `checkPromotions` flag to the `loadOrders` params of `useCustomerOrders` composable

apps/docs/src/getting-started/e-commerce/payments.md
adds key info about integration with app server.
part of #1478
=> docs: app server integration

package.json, pnpm-lock.yaml
=> fix: audit issue with nanoid

.changeset/lazy-phones-build.md, packages/cms-base/components/SwListingProductPrice.vue, templates/vue-demo-store/i18n/de-DE/listing.json, templates/vue-demo-store/i18n/en-GB/listing.json, templates/vue-demo-store/i18n/pl-PL/listing.json, templates/vue-demo-store/nuxt.config.ts
closes: #1524 
also: fixes from price label in product listing product card component
-- Bug fix (non-breaking change that fixes an issue)
=> fix(cms-base): display from price correctly

packages/helpers/src/cms/getCmsLayoutConfiguration.ts
backgroundMedia is assigned twice.
delete one
=> chore: delete duplication of backgroundMedia

examples/snippets-middleware/server/api/translations.get.ts
=> fix(examples): client config for snippets middleware

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yml
=> chore: update templates

apps/docs/.vitepress/sidebar.ts, apps/docs/src/best-practices/testing.md, apps/docs/src/best-practices/testing/accessibility-testing.md
Best practices documentation for axe core accessibility
=> docs: add best practices for axe core accessibility

.github/workflows/accessibility-check.yml, .github/workflows/audit-check.yml, .github/workflows/check-stackblitz-templates.yml, .github/workflows/code-check.yml, .github/workflows/code-examples.yml, .github/workflows/codspeed.yaml, .github/workflows/e2e-tests.yml, .github/workflows/publish-canary.yml, .github/workflows/release.yml, package.json, pnpm-lock.yaml
- bumped `pnpm` to v10
- corepack temporary fix in workflows
=> fix: corepack install and pnpm bump

templates/vue-demo-store/README.md
Adds info about the ISR problem on vercel serverless functions.
=> docs(vue-demo-store): add info about isr issue for serverless functions

apps/e2e-tests/page-objects/CategoryPage.ts, apps/e2e-tests/page-objects/SearchResultPage.ts, apps/e2e-tests/tests/addProductReview.spec.ts, apps/e2e-tests/tests/checkSearch.spec.ts
MAKE E2E GREEN AGAIN ! 
Minor fixes, skip failed tests:
- Add product review scenario https://github.com/shopware/frontends/issues/1679
- Check limit and pagination scenario  https://github.com/shopware/frontends/issues/1678
=> fix(e2e): minor fixes and skip failed tests

.github/workflows/accessibility-check.yml, .github/workflows/audit-check.yml, .github/workflows/check-pr-title.yml, .github/workflows/check-stackblitz-templates.yml, .github/workflows/code-check.yml, .github/workflows/code-examples.yml, .github/workflows/e2e-tests.yml, .github/workflows/failed-job-check.yml, .github/workflows/publish-canary.yml, .github/workflows/release.yml
=> refactor: change actions to linux

.changeset/new-pens-repeat.md, packages/api-gen/src/commands/loadSchema.ts
Create `api-types` folder if not exists
closes #1503
=> feat(api-gen): create `api-types` folder if not exists

.changeset/thirty-cherries-move.md, examples/commercial-customized-products/components/ProductBox.vue, examples/express-checkout/src/App.vue, examples/product-detail-page/components/ProductCard.vue, examples/use-cart/app.vue, packages/cms-base-layer/components/SwProductCard.vue
This pull request includes several changes aimed at improving the accessibility structure of the `ProductCard` component by replacing `h5` HTML tags with `div` tags. The changes span multiple files within the project.
The most important changes include:
File-specific changes:
* Updated `ProductBox.vue` to replace `h5` with `div` for product name display (`examples/commercial-customized-products/components/ProductBox.vue`).
* Updated `App.vue` to replace `h5` with `div` for product name display (`examples/express-checkout/src/App.vue`).
* Updated `ProductCard.vue` to replace `h5` with `div` for product name display (`examples/product-detail-page/components/ProductCard.vue`).
* Updated `app.vue` to replace `h5` with `div` for product name display (`examples/use-cart/app.vue`).
* Updated …
=> fix: product name tag

package.json, pnpm-lock.yaml
=> chore: fix audit

examples/b2b-employee-management/app.vue
This pull request includes a small change to the `examples/b2b-employee-management/app.vue` file. The change adds a `div` with a `test-id` attribute to wrap the existing content, which will help in identifying the wrapper during testing.
* [`examples/b2b-employee-management/app.vue`](diffhunk://#diff-834b3bb48278a9c5aa9a3a74d3c39d951905311649215608742a0d738d985125R9-R16): Added a `div` with `test-id="test-wrapper"` to wrap the existing content for testing purposes.
closes #1702
=> feat: add missing test-wrapper

examples/maintenance-allowlisting/.npmrc, examples/modal-teleport/.npmrc
=> fix: avoid using lock file

apps/docs/src/getting-started/languages.md
Adding information about locally language switching
=> feat: switching language locally

apps/docs/src/resources/troubleshooting.md, apps/docs/src/resources/troubleshooting/CORS.md
exaplains how to work with CORS
see the preview of doc page: https://github.com/shopware/frontends/blob/cd58539c2f87d18609a1f3864a287c34bdd51a6c/apps/docs/src/resources/troubleshooting/CORS.md
=> docs: CORS explained

apps/storybook/stories/layers/layout/components/MainBadge.stories.ts, apps/storybook/stories/layers/layout/components/MainCounter.stories.ts, apps/storybook/uno.config.ts, packages/layers/layout/components/MainBadge.vue, packages/layers/layout/components/MainCounter.vue
Add badge counter component
closes #1769
=> feat: add badge and counter component

.github/ISSUE_TEMPLATE/epic.yaml
=> chore: add epic template

examples/adyen-dropin-component/package.json, examples/amazon-pay-button-example/package.json, examples/api-client-tutorial/src/content/tutorial/2-implementation/1-basics/1-installation/content.md, examples/api-client-tutorial/src/templates/default/package.json, examples/b2b-employee-management/package.json, examples/b2b-quote-management/package.json, examples/blank-playground/package.json, examples/commercial-customized-products/package.json, examples/commercial-quick-order/package.json, examples/express-checkout/package.json, examples/login-form/package.json, examples/maintenance-allowlisting/package.json, examples/modal-teleport/package.json, examples/mollie-credit-card/package.json, examples/multi-sales-channel/package.json, examples/new-api-client/package.json, examples/product-detail-page/package.json, examples/responsive-images/package.json, examples/snippets-middleware/package.json, examples/use-add-to-cart/package.json, examples/use-cart/package.json, examples/use-checkout/package.json, package.json, packages/cms-base-layer/package.json, packages/composables/package.json, packages/nuxt-module/package.json, pnpm-lock.yaml, templates/vue-blank/package.json, templates/vue-demo-store/package.json, templates/vue-vite-blank/package.json
bumped dependencies and fixed building issue with intlify
=> fix: audit issues and build

apps/storybook/stories/layers/form/components/IconButton.stories.ts, apps/storybook/uno.config.ts, packages/layers/form/components/IconButton.vue
* [`packages/layers/form/components/IconButton.vue`](diffhunk://#diff-420f97997d59260da3862ec1f2c7d0bf10c68a577765f2d3e31696bf072f81deR1-R28): Added new props for `type` and `disabled`, and defined corresponding styles for different button types.
Storybook updates:
* [`apps/storybook/stories/layers/form/components/IconButton.stories.ts`](diffhunk://#diff-924a95df4575258ec2f0756007a1b2c5d18653b415ec7f6e11f460d9f7a64e4aR1-R26): Added a new story for the `IconButton` component, including metadata and a primary story example.
Uno configuration updates:
* [`apps/storybook/uno.config.ts`](diffhunk://#diff-b10b67f1746e75f707a9a5e2ddac2c5219a612d6a9be50dc302da071797723deR12-R55): Updated the theme colors with new primary, secondary, and tertiary color definitions, along with their hover and …
=> feat: add IconButton component with styling and Storybook integration

examples/multi-sales-channel/nuxt.config.ts, examples/multi-sales-channel/package.json, examples/multi-sales-channel/pages/[...all].vue, pnpm-lock.yaml
This pull request introduces updates to the multi-sales-channel example, focusing on improving functionality, updating dependencies, and enhancing the user interface. 
closes #1840
=> feat: enhance multi-sales-channel example

.changeset/fine-bobcats-travel.md, templates/vue-demo-store/pages/account/index.vue
This pull request removes the payment section from the account dashboard in the `vue-demo-store` template. 
* Updated the layout of the account dashboard by making the profile section (`<div class="w-1/2">`) take up the full width (`<div class="w-full">`) after removing the payment section. (`templates/vue-demo-store/pages/account/index.vue`, [templates/vue-demo-store/pages/account/index.vueL76-R75](diffhunk://#diff-a505ede7c351ad56d267b5ec68a8d4bc19f214bad53f43e0d995dc68467134ebL76-R75))
* Removed the `userDefaultPaymentMethod` property from the `useUser()` destructure statement, as it is no longer needed. (`templates/vue-demo-store/pages/account/index.vue`, [templates/vue-demo-store/pages/account/index.vueL15](diffhunk://#diff-a505ede7c351ad56d267b5ec68a8d4bc19f214bad53f43e0d995dc6846713 …
=> fix: remove payment section from account dashboard

.changeset/khaki-rocks-taste.md, packages/composables/src/useDefaultOrderAssociations/useDefaultOrderAssociations.test.ts, packages/composables/src/useDefaultOrderAssociations/useDefaultOrderAssociations.ts
=> fix(composables): order details default association

templates/vue-demo-store/app/components/account/AccountRegisterForm.vue
=> fix: revert missing vat id field

.changeset/shy-phones-fetch.md, templates/vue-demo-store/app/pages/checkout/index.vue
=> fix: disable place order button during loading state

templates/vue-starter-template/app/components/form/Checkbox.vue
=> feat: add checkbox component
